import { Product } from './types';

export const MARKET_PRODUCTS_6: Product[] = [
  { id: 'pasta-mkt', name: 'PASTA', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'pasta-ndogo-mkt', name: 'PASTA NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'pears-mkt', name: 'PEARS', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'pears-ndogo-mkt', name: 'PEARS NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'peas-mkt', name: 'PEAS', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'peas-ndogo-mkt', name: 'PEAS NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'pelican-mkt', name: 'PELICAN', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'pelican-ndogo-mkt', name: 'PELICAN NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pepsi-mkt', name: 'PEPSI', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pepsi-ndogo-mkt', name: 'PEPSI NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'peremende-mkt', name: 'PEREMENDE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'peremende-ndogo-mkt', name: 'PEREMENDE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'perfume-mkt', name: 'PERFUME', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'perfume-ndogo-mkt', name: 'PERFUME NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'pete-mkt', name: 'PETE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'pete-ndogo-mkt', name: 'PETE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'picha-mkt', name: 'PICHA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'picha-ndogo-mkt', name: 'PICHA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'pilau-mkt', name: 'PILAU', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'pilau-ndogo-mkt', name: 'PILAU NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'pilipili-mkt', name: 'PILIPILI', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pilipili-ndogo-mkt', name: 'PILIPILI NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pipi-mkt', name: 'PIPI', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pipi-ndogo-mkt', name: 'PIPI NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pishori-mkt', name: 'PISHORI', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'pishori-ndogo-mkt', name: 'PISHORI NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'plate-mkt', name: 'PLATE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'plate-ndogo-mkt', name: 'PLATE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'plus-mkt', name: 'PLUS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'plus-ndogo-mkt', name: 'PLUS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'poda-mkt', name: 'PODA', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'poda-ndogo-mkt', name: 'PODA NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'popcorn-mkt', name: 'POPCORN', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'popcorn-ndogo-mkt', name: 'POPCORN NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'potato-mkt', name: 'POTATO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'potato-ndogo-mkt', name: 'POTATO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'power-mkt', name: 'POWER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'power-ndogo-mkt', name: 'POWER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'prawn-mkt', name: 'PRAWN', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'prawn-ndogo-mkt', name: 'PRAWN NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'prestige-mkt', name: 'PRESTIGE', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'prestige-ndogo-mkt', name: 'PRESTIGE NDOGO', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'price-mkt', name: 'PRICE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'price-ndogo-mkt', name: 'PRICE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pride-mkt', name: 'PRIDE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pride-ndogo-mkt', name: 'PRIDE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'protex-mkt', name: 'PROTEX', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'protex-ndogo-mkt', name: 'PROTEX NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'puff-mkt', name: 'PUFF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'puff-ndogo-mkt', name: 'PUFF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pumzi-mkt', name: 'PUMZI', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pumzi-ndogo-mkt', name: 'PUMZI NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pure-mkt', name: 'PURE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'pure-ndogo-mkt', name: 'PURE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'pweza-mkt', name: 'PWEZA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'pweza-ndogo-mkt', name: 'PWEZA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'quaker-mkt', name: 'QUAKER', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'quaker-ndogo-mkt', name: 'QUAKER NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'queen-mkt', name: 'QUEEN', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'queen-ndogo-mkt', name: 'QUEEN NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'r-mkt', name: 'R', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'r-ndogo-mkt', name: 'R NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'radox-mkt', name: 'RADOX', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'radox-ndogo-mkt', name: 'RADOX NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'raid-mkt', name: 'RAID', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'raid-ndogo-mkt', name: 'RAID NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'rainbow-mkt', name: 'RAINBOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rainbow-ndogo-mkt', name: 'RAINBOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'raisi-mkt', name: 'RAISI', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'raisi-ndogo-mkt', name: 'RAISI NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ram-mkt', name: 'RAM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ram-ndogo-mkt', name: 'RAM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ras-mkt', name: 'RAS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ras-ndogo-mkt', name: 'RAS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ray-mkt', name: 'RAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ray-ndogo-mkt', name: 'RAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'razor-mkt', name: 'RAZOR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'razor-ndogo-mkt', name: 'RAZOR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'red-mkt', name: 'RED', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'red-ndogo-mkt', name: 'RED NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'redbull-mkt', name: 'REDBULL', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'redbull-ndogo-mkt', name: 'REDBULL NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rejoice-mkt', name: 'REJOICE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'rejoice-ndogo-mkt', name: 'REJOICE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'rem-mkt', name: 'REM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rem-ndogo-mkt', name: 'REM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rexona-mkt', name: 'REXONA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'rexona-ndogo-mkt', name: 'REXONA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'rhino-mkt', name: 'RHINO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rhino-ndogo-mkt', name: 'RHINO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ribena-mkt', name: 'RIBENA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'ribena-ndogo-mkt', name: 'RIBENA NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rice-mkt', name: 'RICE', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'rice-ndogo-mkt', name: 'RICE NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'rich-mkt', name: 'RICH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rich-ndogo-mkt', name: 'RICH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rico-mkt', name: 'RICO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rico-ndogo-mkt', name: 'RICO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rid-mkt', name: 'RID', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'rid-ndogo-mkt', name: 'RID NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
];
