import { Product } from './types';

export const MARKET_PRODUCTS_4: Product[] = [
  { id: 'lady-gay-zinc-zinc-zinc-zinc-mkt', name: 'LADY GAY ZINC ZINC ZINC ZINC MKT', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-oil', name: 'LADY GAY ZINC ZINC ZINC ZINC OIL', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-oil-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC OIL NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-powder', name: 'LADY GAY ZINC ZINC ZINC ZINC POWDER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-powder-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC POWDER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-soap', name: 'LADY GAY ZINC ZINC ZINC ZINC SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-soap-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-talc', name: 'LADY GAY ZINC ZINC ZINC ZINC TALC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-talc-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC TALC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-vaseline', name: 'LADY GAY ZINC ZINC ZINC ZINC VASELINE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-vaseline-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC VASELINE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-wash', name: 'LADY GAY ZINC ZINC ZINC ZINC WASH', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-wash-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC WASH NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-water', name: 'LADY GAY ZINC ZINC ZINC ZINC WATER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-water-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC WATER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-white', name: 'LADY GAY ZINC ZINC ZINC ZINC WHITE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-white-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC WHITE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-yellow', name: 'LADY GAY ZINC ZINC ZINC ZINC YELLOW', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-zinc-yellow-ndogo', name: 'LADY GAY ZINC ZINC ZINC ZINC YELLOW NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lavender-mkt', name: 'LAVENDER', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'lifeboy-mkt', name: 'LIFEBOY', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'lifeboy-ndogo-mkt', name: 'LIFEBOY NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'likizo-mkt', name: 'LIKIZO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'likizo-ndogo-mkt', name: 'LIKIZO NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'limao-kopo', name: 'LIMAO KOPO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'limao-robo', name: 'LIMAO ROBO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'limao-unga', name: 'LIMAO UNGA', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'listerine-mkt', name: 'LISTERINE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'listerine-ndogo-mkt', name: 'LISTERINE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'lux-mkt', name: 'LUX', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'lux-ndogo-mkt', name: 'LUX NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mafuta-ya-nazi-mkt', name: 'MAFUTA YA NAZI', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mafuta-ya-nazi-ndogo', name: 'MAFUTA YA NAZI NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mafuta-ya-zaituni-mkt', name: 'MAFUTA YA ZAITUNI', category: 'African Market', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mafuta-ya-zaituni-ndogo', name: 'MAFUTA YA ZAITUNI NDOGO', category: 'African Market', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'magadi-mkt', name: 'MAGADI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'magadi-ndogo-mkt', name: 'MAGADI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'maharage-mkt', name: 'MAHARAGE', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'maharage-ndogo-mkt', name: 'MAHARAGE NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'maize-flour-mkt', name: 'MAIZE FLOUR', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'maize-flour-ndogo-mkt', name: 'MAIZE FLOUR NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'majani-ya-chai-mkt', name: 'MAJANI YA CHAI', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'majani-ya-chai-ndogo-mkt', name: 'MAJANI YA CHAI NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'makaa-mkt', name: 'MAKAA', category: 'African Market', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'makaa-ndogo-mkt', name: 'MAKAA NDOGO', category: 'African Market', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'makande-mkt', name: 'MAKANDE', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'makande-ndogo-mkt', name: 'MAKANDE NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'malta-mkt', name: 'MALTA', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'malta-ndogo-mkt', name: 'MALTA NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mamasita-mkt', name: 'MAMASITA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mamasita-ndogo-mkt', name: 'MAMASITA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mandazi-mkt', name: 'MANDAZI', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mandazi-ndogo-mkt', name: 'MANDAZI NDOGO', category: 'African Market', price: 300, unit: 'pc', isAvailable: true },
  { id: 'manga-mkt', name: 'MANGA', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'manga-ndogo-mkt', name: 'MANGA NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'manjano-mkt', name: 'MANJANO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'manjano-ndogo-mkt', name: 'MANJANO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mapera-mkt', name: 'MAPERA', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mapera-ndogo-mkt', name: 'MAPERA NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'marashi-mkt', name: 'MARASHI', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'marashi-ndogo-mkt', name: 'MARASHI NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'maridadi-mkt', name: 'MARIDADI', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'maridadi-ndogo-mkt', name: 'MARIDADI NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'masala-mkt', name: 'MASALA', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'masala-ndogo-mkt', name: 'MASALA NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'matunda-mkt', name: 'MATUNDA', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'matunda-ndogo-mkt', name: 'MATUNDA NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mbegu-za-mboga-mkt', name: 'MBEGU ZA MBOGA', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mbegu-za-mboga-ndogo-mkt', name: 'MBEGU ZA MBOGA NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mchele-mkt', name: 'MCHELE', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'mchele-ndogo-mkt', name: 'MCHELE NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mchuzi-mkt', name: 'MCHUZI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mchuzi-ndogo-mkt', name: 'MCHUZI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mdalasini-mkt', name: 'MDALASINI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mdalasini-ndogo-mkt', name: 'MDALASINI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mdomo-mkt', name: 'MDOMO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mdomo-ndogo-mkt', name: 'MDOMO NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'medicated-soap-mkt', name: 'MEDICATED SOAP', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'medicated-soap-ndogo-mkt', name: 'MEDICATED SOAP NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mems-mkt', name: 'MEMS', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mems-ndogo-mkt', name: 'MEMS NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mende-mkt', name: 'MENDE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mende-ndogo-mkt', name: 'MENDE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mennen-mkt', name: 'MENNEN', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mennen-ndogo-mkt', name: 'MENNEN NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'menthol-mkt', name: 'MENTHOL', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'menthol-ndogo-mkt', name: 'MENTHOL NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mguu-mkt', name: 'MGUU', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mguu-ndogo-mkt', name: 'MGUU NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mkaa-mkt', name: 'MKAA', category: 'African Market', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mkaa-ndogo-mkt', name: 'MKAA NDOGO', category: 'African Market', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mkate-mkt', name: 'MKATE', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mkate-ndogo-mkt', name: 'MKATE NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mkebe-mkt', name: 'MKEBE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mkebe-ndogo-mkt', name: 'MKEBE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mkia-mkt', name: 'MKIA', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mkia-ndogo-mkt', name: 'MKIA NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mkoba-mkt', name: 'MKOBA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mkoba-ndogo-mkt', name: 'MKOBA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
];
