import { Product } from './types';

export const MARKET_PRODUCTS_11: Product[] = [
  { id: 'star-mkt', name: 'STAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'star-ndogo-mkt', name: 'STAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stare-mkt', name: 'STARE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stare-ndogo-mkt', name: 'STARE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'start-mkt', name: 'START', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'start-ndogo-mkt', name: 'START NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'state-mkt', name: 'STATE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'state-ndogo-mkt', name: 'STATE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'station-mkt', name: 'STATION', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'station-ndogo-mkt', name: 'STATION NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stay-mkt', name: 'STAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stay-ndogo-mkt', name: 'STAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'steady-mkt', name: 'STEADY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'steady-ndogo-mkt', name: 'STEADY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'steak-mkt', name: 'STEAK', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true, sku: 'STK933355228877' },
  { id: 'steak-ndogo-mkt', name: 'STEAK NDOGO', category: 'Butchery', price: 8500, unit: 'pc', isAvailable: true },
  { id: 'steam-mkt', name: 'STEAM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'steam-ndogo-mkt', name: 'STEAM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'steel-mkt', name: 'STEEL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'steel-ndogo-mkt', name: 'STEEL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'steep-mkt', name: 'STEEP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'steep-ndogo-mkt', name: 'STEEP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stem-mkt', name: 'STEM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stem-ndogo-mkt', name: 'STEM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'step-mkt', name: 'STEP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'step-ndogo-mkt', name: 'STEP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stick-mkt', name: 'STICK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stick-ndogo-mkt', name: 'STICK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stiff-mkt', name: 'STIFF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stiff-ndogo-mkt', name: 'STIFF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'still-mkt', name: 'STILL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'still-ndogo-mkt', name: 'STILL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stock-mkt', name: 'STOCK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stock-ndogo-mkt', name: 'STOCK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stone-mkt', name: 'STONE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stone-ndogo-mkt', name: 'STONE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stood-mkt', name: 'STOOD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stood-ndogo-mkt', name: 'STOOD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stop-mkt', name: 'STOP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stop-ndogo-mkt', name: 'STOP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'store-mkt', name: 'STORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'store-ndogo-mkt', name: 'STORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'storm-mkt', name: 'STORM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'storm-ndogo-mkt', name: 'STORM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'story-mkt', name: 'STORY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'story-ndogo-mkt', name: 'STORY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stove-mkt', name: 'STOVE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'stove-ndogo-mkt', name: 'STOVE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'straight-mkt', name: 'STRAIGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'straight-ndogo-mkt', name: 'STRAIGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'strange-mkt', name: 'STRANGE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'strange-ndogo-mkt', name: 'STRANGE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'straw-mkt', name: 'STRAW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'straw-ndogo-mkt', name: 'STRAW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stream-mkt-2', name: 'STREAM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stream-ndogo-mkt-2', name: 'STREAM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'street-mkt', name: 'STREET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'street-ndogo-mkt', name: 'STREET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stretch-mkt', name: 'STRETCH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stretch-ndogo-mkt', name: 'STRETCH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'string-mkt', name: 'STRING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'string-ndogo-mkt', name: 'STRING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'strip-mkt', name: 'STRIP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'strip-ndogo-mkt', name: 'STRIP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'strong-mkt', name: 'STRONG', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'strong-ndogo-mkt', name: 'STRONG NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'struck-mkt', name: 'STRUCK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'struck-ndogo-mkt', name: 'STRUCK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'structure-mkt', name: 'STRUCTURE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'structure-ndogo-mkt', name: 'STRUCTURE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'struggle-mkt', name: 'STRUGGLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'struggle-ndogo-mkt', name: 'STRUGGLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stuck-mkt', name: 'STUCK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stuck-ndogo-mkt', name: 'STUCK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'student-mkt', name: 'STUDENT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'student-ndogo-mkt', name: 'STUDENT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'study-mkt', name: 'STUDY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'study-ndogo-mkt', name: 'STUDY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stuff-mkt', name: 'STUFF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stuff-ndogo-mkt', name: 'STUFF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'subject-mkt', name: 'SUBJECT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'subject-ndogo-mkt', name: 'SUBJECT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'substance-mkt', name: 'SUBSTANCE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'substance-ndogo-mkt', name: 'SUBSTANCE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'success-mkt', name: 'SUCCESS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'success-ndogo-mkt', name: 'SUCCESS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'such-mkt', name: 'SUCH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'such-ndogo-mkt', name: 'SUCH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sudden-mkt', name: 'SUDDEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sudden-ndogo-mkt', name: 'SUDDEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sugar-mkt', name: 'SUGAR', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'sugar-ndogo-mkt', name: 'SUGAR NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'suggest-mkt', name: 'SUGGEST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'suggest-ndogo-mkt', name: 'SUGGEST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'suit-mkt', name: 'SUIT', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'suit-ndogo-mkt', name: 'SUIT NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'summer-mkt', name: 'SUMMER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'summer-ndogo-mkt', name: 'SUMMER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sun-mkt', name: 'SUN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sun-ndogo-mkt', name: 'SUN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
