import { Product } from './types';

export const MARKET_PRODUCTS_14: Product[] = [
  { id: 'tone-mkt', name: 'TONE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tone-ndogo-mkt', name: 'TONE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tongue-mkt', name: 'TONGUE', category: 'Butchery', price: 14000, unit: 'kg', isAvailable: true, sku: 'ULM654321' },
  { id: 'tongue-ndogo-mkt', name: 'TONGUE NDOGO', category: 'Butchery', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'too-mkt', name: 'TOO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'too-ndogo-mkt', name: 'TOO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'took-mkt', name: 'TOOK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'took-ndogo-mkt', name: 'TOOK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tool-mkt', name: 'TOOL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tool-ndogo-mkt', name: 'TOOL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tooth-mkt', name: 'TOOTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tooth-ndogo-mkt', name: 'TOOTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'top-mkt', name: 'TOP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'top-ndogo-mkt', name: 'TOP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'topic-mkt', name: 'TOPIC', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'topic-ndogo-mkt', name: 'TOPIC NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'total-mkt', name: 'TOTAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'total-ndogo-mkt', name: 'TOTAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'touch-mkt', name: 'TOUCH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'touch-ndogo-mkt', name: 'TOUCH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'toward-mkt', name: 'TOWARD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'toward-ndogo-mkt', name: 'TOWARD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'town-mkt', name: 'TOWN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'town-ndogo-mkt', name: 'TOWN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'toy-mkt', name: 'TOY', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'toy-ndogo-mkt', name: 'TOY NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'trace-mkt', name: 'TRACE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trace-ndogo-mkt', name: 'TRACE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'track-mkt', name: 'TRACK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'track-ndogo-mkt', name: 'TRACK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trade-mkt', name: 'TRADE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trade-ndogo-mkt', name: 'TRADE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'traffic-mkt', name: 'TRAFFIC', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'traffic-ndogo-mkt', name: 'TRAFFIC NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trail-mkt', name: 'TRAIL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trail-ndogo-mkt', name: 'TRAIL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'train-mkt', name: 'TRAIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'train-ndogo-mkt', name: 'TRAIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'transportation-mkt', name: 'TRANSPORTATION', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'transportation-ndogo-mkt', name: 'TRANSPORTATION NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trap-mkt', name: 'TRAP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trap-ndogo-mkt', name: 'TRAP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'travel-mkt', name: 'TRAVEL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'travel-ndogo-mkt', name: 'TRAVEL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'treasure-mkt', name: 'TREASURE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'treasure-ndogo-mkt', name: 'TREASURE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tree-mkt', name: 'TREE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tree-ndogo-mkt', name: 'TREE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'triangle-mkt', name: 'TRIANGLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'triangle-ndogo-mkt', name: 'TRIANGLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tribe-mkt', name: 'TRIBE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tribe-ndogo-mkt', name: 'TRIBE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trick-mkt', name: 'TRICK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trick-ndogo-mkt', name: 'TRICK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tried-mkt', name: 'TRIED', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tried-ndogo-mkt', name: 'TRIED NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trip-mkt', name: 'TRIP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trip-ndogo-mkt', name: 'TRIP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'troops-mkt', name: 'TROOPS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'troops-ndogo-mkt', name: 'TROOPS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tropical-mkt', name: 'TROPICAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tropical-ndogo-mkt', name: 'TROPICAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trouble-mkt', name: 'TROUBLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trouble-ndogo-mkt', name: 'TROUBLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'truck-mkt', name: 'TRUCK', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'truck-ndogo-mkt', name: 'TRUCK NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'true-mkt', name: 'TRUE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'true-ndogo-mkt', name: 'TRUE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trunk-mkt', name: 'TRUNK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trunk-ndogo-mkt', name: 'TRUNK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'trust-mkt', name: 'TRUST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'trust-ndogo-mkt', name: 'TRUST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'truth-mkt', name: 'TRUTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'truth-ndogo-mkt', name: 'TRUTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'try-mkt', name: 'TRY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'try-ndogo-mkt', name: 'TRY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tube-mkt', name: 'TUBE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tube-ndogo-mkt', name: 'TUBE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tune-mkt', name: 'TUNE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tune-ndogo-mkt', name: 'TUNE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'turn-mkt', name: 'TURN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'turn-ndogo-mkt', name: 'TURN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'twelve-mkt', name: 'TWELVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'twelve-ndogo-mkt', name: 'TWELVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'twenty-mkt', name: 'TWENTY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'twenty-ndogo-mkt', name: 'TWENTY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'twice-mkt', name: 'TWICE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'twice-ndogo-mkt', name: 'TWICE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'two-mkt', name: 'TWO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'two-ndogo-mkt', name: 'TWO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'type-mkt', name: 'TYPE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'type-ndogo-mkt', name: 'TYPE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'typical-mkt', name: 'TYPICAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'typical-ndogo-mkt', name: 'TYPICAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'u-mkt', name: 'U', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'u-ndogo-mkt', name: 'U NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ubuyu-mkt', name: 'UBUYU', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'ubuyu-ndogo-mkt', name: 'UBUYU NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'ugali-mkt', name: 'UGALI', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'ugali-ndogo-mkt', name: 'UGALI NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
];
