import { Product } from './types';

export const MARKET_PRODUCTS_17: Product[] = [
  { id: 'win-mkt', name: 'WIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'win-ndogo-mkt', name: 'WIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wind-mkt', name: 'WIND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wind-ndogo-mkt', name: 'WIND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'window-mkt', name: 'WINDOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'window-ndogo-mkt', name: 'WINDOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wing-mkt', name: 'WING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wing-ndogo-mkt', name: 'WING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'winter-mkt', name: 'WINTER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'winter-ndogo-mkt', name: 'WINTER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wire-mkt', name: 'WIRE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wire-ndogo-mkt', name: 'WIRE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wise-mkt', name: 'WISE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wise-ndogo-mkt', name: 'WISE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wish-mkt', name: 'WISH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wish-ndogo-mkt', name: 'WISH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'with-mkt', name: 'WITH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'with-ndogo-mkt', name: 'WITH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'within-mkt', name: 'WITHIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'within-ndogo-mkt', name: 'WITHIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'without-mkt', name: 'WITHOUT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'without-ndogo-mkt', name: 'WITHOUT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wolf-mkt', name: 'WOLF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wolf-ndogo-mkt', name: 'WOLF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'woman-mkt', name: 'WOMAN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'woman-ndogo-mkt', name: 'WOMAN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'women-mkt', name: 'WOMEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'women-ndogo-mkt', name: 'WOMEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'won-mkt', name: 'WON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'won-ndogo-mkt', name: 'WON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wonder-mkt', name: 'WONDER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wonder-ndogo-mkt', name: 'WONDER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wonderful-mkt', name: 'WONDERFUL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wonderful-ndogo-mkt', name: 'WONDERFUL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wood-mkt', name: 'WOOD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wood-ndogo-mkt', name: 'WOOD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wooden-mkt', name: 'WOODEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wooden-ndogo-mkt', name: 'WOODEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wool-mkt', name: 'WOOL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wool-ndogo-mkt', name: 'WOOL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'word-mkt', name: 'WORD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'word-ndogo-mkt', name: 'WORD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wore-mkt', name: 'WORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wore-ndogo-mkt', name: 'WORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'work-mkt', name: 'WORK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'work-ndogo-mkt', name: 'WORK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'worker-mkt', name: 'WORKER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'worker-ndogo-mkt', name: 'WORKER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'world-mkt', name: 'WORLD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'world-ndogo-mkt', name: 'WORLD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'worry-mkt', name: 'WORRY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'worry-ndogo-mkt', name: 'WORRY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'worse-mkt', name: 'WORSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'worse-ndogo-mkt', name: 'WORSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'worth-mkt', name: 'WORTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'worth-ndogo-mkt', name: 'WORTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'would-mkt', name: 'WOULD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'would-ndogo-mkt', name: 'WOULD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wrapped-mkt', name: 'WRAPPED', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wrapped-ndogo-mkt', name: 'WRAPPED NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'write-mkt', name: 'WRITE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'write-ndogo-mkt', name: 'WRITE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'writer-mkt', name: 'WRITER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'writer-ndogo-mkt', name: 'WRITER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'writing-mkt', name: 'WRITING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'writing-ndogo-mkt', name: 'WRITING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'written-mkt', name: 'WRITTEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'written-ndogo-mkt', name: 'WRITTEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wrong-mkt', name: 'WRONG', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wrong-ndogo-mkt', name: 'WRONG NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wrote-mkt', name: 'WROTE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wrote-ndogo-mkt', name: 'WROTE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'x-mkt', name: 'X', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'x-ndogo-mkt', name: 'X NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'y-mkt', name: 'Y', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'y-ndogo-mkt', name: 'Y NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yard-mkt', name: 'YARD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yard-ndogo-mkt', name: 'YARD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'year-mkt', name: 'YEAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'year-ndogo-mkt', name: 'YEAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yellow-mkt', name: 'YELLOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yellow-ndogo-mkt', name: 'YELLOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yes-mkt', name: 'YES', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yes-ndogo-mkt', name: 'YES NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yesterday-mkt', name: 'YESTERDAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yesterday-ndogo-mkt', name: 'YESTERDAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yet-mkt', name: 'YET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yet-ndogo-mkt', name: 'YET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'you-mkt', name: 'YOU', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'you-ndogo-mkt', name: 'YOU NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'young-mkt', name: 'YOUNG', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'young-ndogo-mkt', name: 'YOUNG NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'your-mkt', name: 'YOUR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'your-ndogo-mkt', name: 'YOUR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'yourself-mkt', name: 'YOURSELF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'yourself-ndogo-mkt', name: 'YOURSELF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'youth-mkt', name: 'YOUTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'youth-ndogo-mkt', name: 'YOUTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'z-mkt', name: 'Z', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'z-ndogo-mkt', name: 'Z NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'zebra-mkt', name: 'ZEBRA', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'zebra-ndogo-mkt', name: 'ZEBRA NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'zero-mkt', name: 'ZERO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'zero-ndogo-mkt', name: 'ZERO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'zoo-mkt', name: 'ZOO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'zoo-ndogo-mkt', name: 'ZOO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
