import { Product } from './types';

export const MARKET_PRODUCTS_2: Product[] = [
  { id: 'handy-andy-lavender', name: 'HANDY ANDY LAVENDER', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/handy-andy-lavender/400/400' },
  { id: 'astra-hand-wash-aloe-500ml', name: 'ASTRA HAND WASH ALOE VERA 500 MLS', category: 'Specialty', price: 3500, unit: '500ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/astra-hand-wash-aloe/400/400' },
  { id: 'happic-ndogo', name: 'HAPPIC NDOGO', category: 'Specialty', price: 7500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/happic-small/400/400' },
  { id: 'happic-kubwa', name: 'HAPPIC KUBWA', category: 'Specialty', price: 7500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/happic-large/400/400' },
  { id: 'harpic-500mls', name: 'HARPIC 500MLS', category: 'Specialty', price: 5000, unit: '500ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/harpic-500ml/400/400' },
  { id: 'harpic-750mls-mkt', name: 'HARPIC 750MLS', category: 'Specialty', price: 6500, unit: '750ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/harpic-750ml/400/400' },
  { id: 'heinz-beans', name: 'HEINZ BEANS', category: 'Specialty', price: 5500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/heinz-beans/400/400' },
  { id: 'hiliki-kopo', name: 'HILIKI KOPO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hiliki-jar/400/400' },
  { id: 'hiliki-robo', name: 'HILIKI ROBO', category: 'Specialty', price: 16000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hiliki-robo/400/400' },
  { id: 'hill-1lt-ctn', name: 'HILL 1LT CTN', category: 'Specialty', price: 3000, unit: 'ctn', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-1l-carton/400/400' },
  { id: 'hill-1-5-ctn', name: 'HILL 1.5 CTN', category: 'Specialty', price: 4000, unit: 'ctn', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-1-5l-carton/400/400' },
  { id: 'hill-12lts', name: 'HILL 12LTS', category: 'Specialty', price: 4000, unit: '12L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-12l/400/400' },
  { id: 'hill-16lts', name: 'HILL 16LTS', category: 'Specialty', price: 7500, unit: '16L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-16l/400/400' },
  { id: 'hill-20lts', name: 'HILL 20LTS', category: 'Specialty', price: 8500, unit: '20L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-20l/400/400' },
  { id: 'hill-500-mls', name: 'HILL 500 MLS', category: 'Specialty', price: 4000, unit: '500ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-500ml/400/400' },
  { id: 'hill-oil-1l', name: 'HILL OIL 1L', category: 'African Market', price: 9000, unit: '1L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-oil-1l/400/400' },
  { id: 'hill-oil-3l', name: 'HILL OIL 3L', category: 'African Market', price: 25000, unit: '3L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-oil-3l/400/400' },
  { id: 'hill-oil-5l', name: 'HILL OIL 5L', category: 'African Market', price: 36000, unit: '5L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-oil-5l/400/400' },
  { id: 'hill-stiff-wate', name: 'HILL STIFF WATE', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-stiff-water/400/400' },
  { id: 'hill-spakling-330mls', name: 'HILL SPAKLING 330MLS', category: 'Specialty', price: 18000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hill-sparkling-330ml/400/400' },
  { id: 'hit-400mls', name: 'HIT 400MLS', category: 'Specialty', price: 6000, unit: '400ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hit-400ml/400/400' },
  { id: 'hit-lemon-750mls', name: 'HIT LEMON 750MLS', category: 'Specialty', price: 8000, unit: '750ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hit-lemon-750ml/400/400' },
  { id: 'hobby-pomegranate-shower-gel', name: 'HOBBY POMEGRANATE SHOWER GEL', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hobby-pomegranate-shower-gel/400/400' },
  { id: 'hopeca-mkt', name: 'HOPECA', category: 'African Market', price: 30000, unit: 'kg', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hopeca/400/400' },
  { id: 'hot-chil', name: 'HOT CHIL', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hot-chili/400/400' },
  { id: 'hq-pads', name: 'HQ PADS', category: 'Specialty', price: 4000, unit: 'pack', isAvailable: true, imageUrl: 'https://picsum.photos/seed/hq-pads/400/400' },
  { id: 'huggies-kubwa-mkt', name: 'HUGGIES KUBWA', category: 'Specialty', price: 55000, unit: 'pack', isAvailable: true, imageUrl: 'https://picsum.photos/seed/huggies-large/400/400' },
  { id: 'huggies-ndogo-mkt', name: 'HUGGIES NDOGO', category: 'Specialty', price: 23000, unit: 'pack', isAvailable: true, imageUrl: 'https://picsum.photos/seed/huggies-small/400/400' },
  { id: 'icing-sugar-mkt', name: 'ICING SUGAR', category: 'Specialty', price: 3500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/icing-sugar/400/400' },
  { id: 'ikoda-spices-mkt', name: 'IKODA SPICES', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/ikoda-spices/400/400' },
  { id: 'ikram-oil-5lt', name: 'IKRAM OIL 5LT', category: 'African Market', price: 32000, unit: '5L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/ikram-oil-5l/400/400' },
  { id: 'imperial-leather', name: 'IMPERIAL LEATHER', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/imperial-leather-soap/400/400' },
  { id: 'jamaa-whitewash-kleesofty', name: 'JAMAA/WHITEWASH/KLEESOFTY', category: 'Specialty', price: 3600, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/jamaa-whitewash/400/400' },
  { id: 'jet-1lt', name: 'JET 1LT', category: 'Specialty', price: 5000, unit: '1L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/jet-1l/400/400' },
  { id: 'jet-dishwash-5lt', name: 'JET DISHWASH 5LT', category: 'Specialty', price: 10500, unit: '5L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/jet-dishwash-5l/400/400' },
  { id: 'jik-250mls', name: 'JIK 250MLS', category: 'Specialty', price: 3500, unit: '250ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/jik-250ml/400/400' },
  { id: 'jik-750mls', name: 'JIK 750MLS', category: 'Specialty', price: 7500, unit: '750ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/jik-750ml/400/400' },
  { id: 'kahawa-africafe-100gm', name: 'KAHAWA - AFRICAFE 100GM', category: 'African Market', price: 13000, unit: '100g', isAvailable: true, imageUrl: 'https://picsum.photos/seed/africafe-100g/400/400' },
  { id: 'kahawa-africafe-50gm', name: 'KAHAWA - AFRICAFE 50GM', category: 'African Market', price: 8000, unit: '50g', isAvailable: true, imageUrl: 'https://picsum.photos/seed/africafe-50g/400/400' },
  { id: 'kahawa-africafe-mkanda', name: 'KAHAWA - AFRICAFE MKANDA', category: 'African Market', price: 300, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/africafe-mkanda/400/400' },
  { id: 'kahawa-africafe-250gm', name: 'KAHAWA AFRICAFE 250GM', category: 'African Market', price: 25000, unit: '250g', isAvailable: true, imageUrl: 'https://picsum.photos/seed/africafe-250g/400/400' },
  { id: 'kahawa-halis', name: 'KAHAWA HALIS', category: 'African Market', price: 3500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kahawa-halisi/400/400' },
  { id: 'kamba-mazoezi', name: 'KAMBA MAZOEZI', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kamba-mazoezi/400/400' },
  { id: 'kamba-nguo', name: 'KAMBA NGUO', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kamba-nguo/400/400' },
  { id: 'karafuu-kopo', name: 'KARAFUU KOPO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/karafuu-jar/400/400' },
  { id: 'karafuu-robo', name: 'KARAFUU ROBO', category: 'Specialty', price: 12000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/karafuu-robo/400/400' },
  { id: 'karafuu-unga', name: 'KARAFUU UNGA', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/karafuu-powder/400/400' },
  { id: 'karanga-lucia', name: 'KARANGA LUCIA', category: 'African Market', price: 3600, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/karanga-lucia/400/400' },
  { id: 'karanga-za-mayai', name: 'KARANGA ZA MAYAI', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/karanga-za-mayai/400/400' },
  { id: 'kashai-senene-kubwa', name: 'KASHAI SENENE KUBWA', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kashai-senene-large/400/400' },
  { id: 'kashai-senene-ndogo', name: 'KASHAI SENENE NDOGO', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kashai-senene-small/400/400' },
  { id: 'kashai-tende-kubwa', name: 'KASHAI TENDE KUBWA', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kashai-tende-large/400/400' },
  { id: 'kashai-tende-ndogo', name: 'KASHAI TENDE NDOGO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kashai-tende-small/400/400' },
  { id: 'ketchep-kubwa-1-8lt', name: 'KETCHEP KUBWA 1.8LT', category: 'Specialty', price: 23000, unit: '1.8L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/ketchup-large/400/400' },
  { id: 'key-holder', name: 'KEY HOLDER', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/key-holder/400/400' },
  { id: 'kifaa-kusaga-karoti-nd', name: 'KIFAA KUSAGA KAROTI ND', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kifaa-kusaga-karoti/400/400' },
  { id: 'kilian-beef-spices-mkt', name: 'KILIAN BEEF SPICES', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-beef-spices/400/400' },
  { id: 'kilian-black-pepper-7000', name: 'KILIAN BLACK PEPPER 7000', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-black-pepper/400/400' },
  { id: 'kilian-cardamon-7000', name: 'KILIAN CARDAMON 7000', category: 'Specialty', price: 11000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-cardamon/400/400' },
  { id: 'kilian-cloves-6000', name: 'KILIAN CLOVES 6000', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-cloves/400/400' },
  { id: 'kilian-garlic-6000', name: 'KILIAN GARLIC 6000', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-garlic/400/400' },
  { id: 'black-jack-biscuit', name: 'BLACK JACK BISCUIT', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/black-jack-biscuit/400/400' },
  { id: 'kilian-mixed-masala-5000', name: 'KILIAN MIXED MASALA 5000', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-mixed-masala/400/400' },
  { id: 'kilian-chicken-masala-5000', name: 'KILIAN CHICKEN MASALA 5000', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-chicken-masala/400/400' },
  { id: 'kilian-coriander-cumin-5000', name: 'KILIAN CORIANDER CUMIN 5000', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-coriander-cumin/400/400' },
  { id: 'kilian-fish-masala-mkt', name: 'KILIAN FISH MASALA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-fish-masala/400/400' },
  { id: 'kilian-ginger-6000', name: 'KILIAN GINGER 6000', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-ginger/400/400' },
  { id: 'kilian-oregano-7000', name: 'KILIAN OREGANO 7000', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-oregano/400/400' },
  { id: 'kilian-paplika-7000', name: 'KILIAN PAPLIKA 7000', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-paprika/400/400' },
  { id: 'kilian-pilau-masala-5000', name: 'KILIAN PILAU MASALA 5000', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-pilau-masala/400/400' },
  { id: 'kilian-cinamon-5000', name: 'KILIAN CINAMON5000', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-cinnamon/400/400' },
  { id: 'kilian-turmeric-mkt', name: 'KILIAN TURMERIC', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-turmeric/400/400' },
  { id: 'kilian-white-pepper-6000', name: 'KILIAN WHITE PEPPER 6000', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilian-white-pepper/400/400' },
  { id: 'kilimanjaro-1-5-lt-ctn', name: 'KILIMANJARO 1.5 LT CTN', category: 'Specialty', price: 5500, unit: 'ctn', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-1-5l-carton/400/400' },
  { id: 'kilimanjaro-12lts-mkt', name: 'KILIMANJARO 12LTS', category: 'Specialty', price: 4000, unit: '12L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-12l/400/400' },
  { id: 'kilimanjaro-18-9lts', name: 'KILIMANJARO 18.9LTS', category: 'Specialty', price: 8000, unit: '18.9L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-18-9l/400/400' },
  { id: 'kilimanjaro-1lt-ctn-mkt', name: 'KILIMANJARO 1LT CTN', category: 'Specialty', price: 3500, unit: 'ctn', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-1l-carton/400/400' },
  { id: 'kilimanjaro-500mls-mkt', name: 'KILIMANJARO 500MLS', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-500ml/400/400' },
  { id: 'kilimanjaro-hibscuss-tea-bag', name: 'KILIMANJARO HIBSCUSS/TEA BAG', category: 'African Market', price: 4000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-hibiscus-tea/400/400' },
  { id: 'kilimanjaro-tea-bag-mkt', name: 'KILIMANJARO TEA BAG', category: 'African Market', price: 4500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-tea-bag/400/400' },
  { id: 'kilimanjaro-water-500mls', name: 'KILIMANJARO WATER 500MLS', category: 'Specialty', price: 4000, unit: '500ml', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kilimanjaro-water-500ml/400/400' },
  { id: 'killian-garam-masala-5', name: 'KILLIAN GARAM MASALA 5', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/killian-garam-masala/400/400' },
  { id: 'killian-white-pepper-mkt', name: 'KILLIAN WHITE PEPPER', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/killian-white-pepper-2/400/400' },
  { id: 'kimbo', name: 'KIMBO', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kimbo-cooking-fat/400/400' },
  { id: 'king-limao-ndoo', name: 'KING LIMAO NDOO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/king-limao-bucket/400/400' },
  { id: 'king-limao-roba', name: 'KING LIMAO ROBA', category: 'Specialty', price: 35000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/king-limao-roba/400/400' },
  { id: 'kisima-16lts', name: 'KISIMA 16LTS', category: 'Specialty', price: 6500, unit: '16L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kisima-16l/400/400' },
  { id: 'kisima-20lts', name: 'KISIMA 20LTS', category: 'Specialty', price: 7500, unit: '20L', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kisima-20l/400/400' },
  { id: 'kitambaa-jikoni', name: 'KITAMBAA JIKONI', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kitambaa-jikoni/400/400' },
  { id: 'kiwi-1500', name: 'KIWI 1500', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kiwi-1500/400/400' },
  { id: 'kiwi-4500', name: 'KIWI 4500', category: 'Specialty', price: 4500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kiwi-4500/400/400' },
  { id: 'kiwi-6000', name: 'KIWI 6000', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kiwi-6000/400/400' },
  { id: 'kiwi-kawaida', name: 'KIWI KAWAIDA', category: 'Specialty', price: 4500, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kiwi-kawaida/400/400' },
  { id: 'kiwi-ndogo', name: 'KIWI NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kiwi-small/400/400' },
  { id: 'kleesoft-kiroba', name: 'KLEESOFT KIROBA', category: 'Specialty', price: 12750, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kleesoft-kiroba/400/400' },
  { id: 'kleesoft-mche', name: 'KLEESOFT MCHE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kleesoft-mche/400/400' },
  { id: 'kleesoft-ndoo', name: 'KLEESOFT NDOO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kleesoft-bucket/400/400' },
  { id: 'klin-ndoo', name: 'KLIN NDOO', category: 'Specialty', price: 14000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/klin-bucket/400/400' },
  { id: 'kofia-10000', name: 'KOFIA 10000', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kofia-10000/400/400' },
  { id: 'kopo-ogea-2000', name: 'KOPO OGEA 2000', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true, imageUrl: 'https://picsum.photos/seed/kopo-ogea/400/400' },
];
