import { Product } from './types';

export const MARKET_PRODUCTS_12: Product[] = [
  { id: 'sunlight-mkt', name: 'SUNLIGHT', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'sunlight-ndogo-mkt', name: 'SUNLIGHT NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'super-mkt', name: 'SUPER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'super-ndogo-mkt', name: 'SUPER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'supper-mkt', name: 'SUPPER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'supper-ndogo-mkt', name: 'SUPPER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'supply-mkt', name: 'SUPPLY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'supply-ndogo-mkt', name: 'SUPPLY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'support-mkt', name: 'SUPPORT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'support-ndogo-mkt', name: 'SUPPORT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'suppose-mkt', name: 'SUPPOSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'suppose-ndogo-mkt', name: 'SUPPOSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sure-mkt', name: 'SURE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sure-ndogo-mkt', name: 'SURE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'surface-mkt', name: 'SURFACE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'surface-ndogo-mkt', name: 'SURFACE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'surprise-mkt', name: 'SURPRISE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'surprise-ndogo-mkt', name: 'SURPRISE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'surround-mkt', name: 'SURROUND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'surround-ndogo-mkt', name: 'SURROUND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'survey-mkt', name: 'SURVEY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'survey-ndogo-mkt', name: 'SURVEY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'swahili-mkt', name: 'SWAHILI', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'swahili-ndogo-mkt', name: 'SWAHILI NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sweet-mkt', name: 'SWEET', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sweet-ndogo-mkt', name: 'SWEET NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'swim-mkt', name: 'SWIM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'swim-ndogo-mkt', name: 'SWIM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'swing-mkt', name: 'SWING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'swing-ndogo-mkt', name: 'SWING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'syllable-mkt', name: 'SYLLABLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'syllable-ndogo-mkt', name: 'SYLLABLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'symbol-mkt', name: 'SYMBOL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'symbol-ndogo-mkt', name: 'SYMBOL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'system-mkt', name: 'SYSTEM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'system-ndogo-mkt', name: 'SYSTEM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 't-mkt', name: 'T', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 't-ndogo-mkt', name: 'T NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'table-mkt', name: 'TABLE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'table-ndogo-mkt', name: 'TABLE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'tail-mkt', name: 'TAIL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tail-ndogo-mkt', name: 'TAIL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'take-mkt', name: 'TAKE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'take-ndogo-mkt', name: 'TAKE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'talk-mkt', name: 'TALK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'talk-ndogo-mkt', name: 'TALK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tall-mkt', name: 'TALL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tall-ndogo-mkt', name: 'TALL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tangawizi-mkt', name: 'TANGAWIZI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'tangawizi-ndogo-mkt', name: 'TANGAWIZI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tank-mkt', name: 'TANK', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'tank-ndogo-mkt', name: 'TANK NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'tape-mkt', name: 'TAPE', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'tape-ndogo-mkt', name: 'TAPE NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'target-mkt', name: 'TARGET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'target-ndogo-mkt', name: 'TARGET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'task-mkt', name: 'TASK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'task-ndogo-mkt', name: 'TASK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'taste-mkt', name: 'TASTE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'taste-ndogo-mkt', name: 'TASTE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'taught-mkt', name: 'TAUGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'taught-ndogo-mkt', name: 'TAUGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tax-mkt', name: 'TAX', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tax-ndogo-mkt', name: 'TAX NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tea-mkt', name: 'TEA', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'tea-ndogo-mkt', name: 'TEA NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'teach-mkt', name: 'TEACH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'teach-ndogo-mkt', name: 'TEACH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'teacher-mkt', name: 'TEACHER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'teacher-ndogo-mkt', name: 'TEACHER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'team-mkt', name: 'TEAM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'team-ndogo-mkt', name: 'TEAM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tear-mkt', name: 'TEAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tear-ndogo-mkt', name: 'TEAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'teeth-mkt', name: 'TEETH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'teeth-ndogo-mkt', name: 'TEETH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tell-mkt', name: 'TELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tell-ndogo-mkt', name: 'TELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'temperature-mkt', name: 'TEMPERATURE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'temperature-ndogo-mkt', name: 'TEMPERATURE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ten-mkt', name: 'TEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ten-ndogo-mkt', name: 'TEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tende-mkt', name: 'TENDE', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'tende-ndogo-mkt', name: 'TENDE NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'term-mkt', name: 'TERM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'term-ndogo-mkt', name: 'TERM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'test-mkt', name: 'TEST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'test-ndogo-mkt', name: 'TEST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'than-mkt', name: 'THAN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'than-ndogo-mkt', name: 'THAN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thank-mkt', name: 'THANK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thank-ndogo-mkt', name: 'THANK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'that-mkt', name: 'THAT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'that-ndogo-mkt', name: 'THAT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'the-mkt', name: 'THE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'the-ndogo-mkt', name: 'THE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'them-mkt', name: 'THEM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'them-ndogo-mkt', name: 'THEM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'themselves-mkt', name: 'THEMSELVES', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'themselves-ndogo-mkt', name: 'THEMSELVES NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
