import { Product } from './types';

export const MARKET_PRODUCTS_16: Product[] = [
  { id: 'war-mkt', name: 'WAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'war-ndogo-mkt', name: 'WAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'warm-mkt', name: 'WARM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'warm-ndogo-mkt', name: 'WARM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'warn-mkt', name: 'WARN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'warn-ndogo-mkt', name: 'WARN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'was-mkt', name: 'WAS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'was-ndogo-mkt', name: 'WAS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wash-mkt', name: 'WASH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wash-ndogo-mkt', name: 'WASH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'waste-mkt', name: 'WASTE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'waste-ndogo-mkt', name: 'WASTE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'watch-mkt', name: 'WATCH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'watch-ndogo-mkt', name: 'WATCH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'water-mkt', name: 'WATER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'water-ndogo-mkt', name: 'WATER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wave-mkt', name: 'WAVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wave-ndogo-mkt', name: 'WAVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'way-mkt', name: 'WAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'way-ndogo-mkt', name: 'WAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'we-mkt', name: 'WE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'we-ndogo-mkt', name: 'WE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'weak-mkt', name: 'WEAK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'weak-ndogo-mkt', name: 'WEAK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wealth-mkt', name: 'WEALTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wealth-ndogo-mkt', name: 'WEALTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wear-mkt', name: 'WEAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wear-ndogo-mkt', name: 'WEAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'weather-mkt', name: 'WEATHER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'weather-ndogo-mkt', name: 'WEATHER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'week-mkt', name: 'WEEK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'week-ndogo-mkt', name: 'WEEK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'weigh-mkt', name: 'WEIGH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'weigh-ndogo-mkt', name: 'WEIGH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'weight-mkt', name: 'WEIGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'weight-ndogo-mkt', name: 'WEIGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'welcome-mkt', name: 'WELCOME', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'welcome-ndogo-mkt', name: 'WELCOME NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'well-mkt', name: 'WELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'well-ndogo-mkt', name: 'WELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'went-mkt', name: 'WENT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'went-ndogo-mkt', name: 'WENT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'were-mkt', name: 'WERE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'were-ndogo-mkt', name: 'WERE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'west-mkt', name: 'WEST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'west-ndogo-mkt', name: 'WEST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'western-mkt', name: 'WESTERN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'western-ndogo-mkt', name: 'WESTERN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wet-mkt', name: 'WET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wet-ndogo-mkt', name: 'WET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whale-mkt', name: 'WHALE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whale-ndogo-mkt', name: 'WHALE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'what-mkt', name: 'WHAT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'what-ndogo-mkt', name: 'WHAT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whatever-mkt', name: 'WHATEVER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whatever-ndogo-mkt', name: 'WHATEVER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wheat-mkt', name: 'WHEAT', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'wheat-ndogo-mkt', name: 'WHEAT NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wheel-mkt', name: 'WHEEL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wheel-ndogo-mkt', name: 'WHEEL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'when-mkt', name: 'WHEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'when-ndogo-mkt', name: 'WHEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whenever-mkt', name: 'WHENEVER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whenever-ndogo-mkt', name: 'WHENEVER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'where-mkt', name: 'WHERE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'where-ndogo-mkt', name: 'WHERE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whether-mkt', name: 'WHETHER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whether-ndogo-mkt', name: 'WHETHER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'which-mkt', name: 'WHICH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'which-ndogo-mkt', name: 'WHICH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'while-mkt', name: 'WHILE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'while-ndogo-mkt', name: 'WHILE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whisper-mkt', name: 'WHISPER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whisper-ndogo-mkt', name: 'WHISPER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whistle-mkt', name: 'WHISTLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whistle-ndogo-mkt', name: 'WHISTLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'white-mkt', name: 'WHITE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'white-ndogo-mkt', name: 'WHITE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'who-mkt', name: 'WHO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'who-ndogo-mkt', name: 'WHO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whole-mkt', name: 'WHOLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whole-ndogo-mkt', name: 'WHOLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whom-mkt', name: 'WHOM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whom-ndogo-mkt', name: 'WHOM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'whose-mkt', name: 'WHOSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'whose-ndogo-mkt', name: 'WHOSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'why-mkt', name: 'WHY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'why-ndogo-mkt', name: 'WHY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wide-mkt', name: 'WIDE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wide-ndogo-mkt', name: 'WIDE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'widely-mkt', name: 'WIDELY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'widely-ndogo-mkt', name: 'WIDELY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wife-mkt', name: 'WIFE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wife-ndogo-mkt', name: 'WIFE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wild-mkt', name: 'WILD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wild-ndogo-mkt', name: 'WILD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'will-mkt', name: 'WILL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'will-ndogo-mkt', name: 'WILL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'willing-mkt', name: 'WILLING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'willing-ndogo-mkt', name: 'WILLING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
