import { Product } from './types';

export const MARKET_PRODUCTS_3: Product[] = [
  { id: 'korie-1lt', name: 'KORIE 1LT', category: 'African Market', price: 9000, unit: '1L', isAvailable: true },
  { id: 'korie-20lt', name: 'KORIE 20LT', category: 'African Market', price: 135000, unit: '20L', isAvailable: true },
  { id: 'korie-3lt', name: 'KORIE 3LT', category: 'African Market', price: 25000, unit: '3L', isAvailable: true },
  { id: 'korie-5lt', name: 'KORIE 5LT', category: 'African Market', price: 36000, unit: '5L', isAvailable: true },
  { id: 'korie-ndogo', name: 'KORIE NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'korie-ndogo-mkt', name: 'KORIE NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'kuku-mkavu', name: 'KUKU MKAVU', category: 'Butchery', price: 25000, unit: 'pc', isAvailable: true },
  { id: 'kuku-wa-kienyeji', name: 'KUKU WA KIENYEJI', category: 'Butchery', price: 25000, unit: 'pc', isAvailable: true },
  { id: 'kuku-wa-kisasa-mkt', name: 'KUKU WA KISASA', category: 'Butchery', price: 13000, unit: 'pc', isAvailable: true },
  { id: 'kunazi', name: 'KUNAZI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'kunjani-mkt', name: 'KUNJANI', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'kunjani-ndogo', name: 'KUNJANI NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'kurunzi-mkt', name: 'KURUNZI', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'kurunzi-ndogo', name: 'KURUNZI NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'kuta-mkt', name: 'KUTA', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'kuta-ndogo', name: 'KUTA NDOGO', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'kwa-ajili-ya-kufuta-vumbi', name: 'KWA AJILI YA KUFUTA VUMBI', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'kweme', name: 'KWEME', category: 'African Market', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'kweme-ndogo', name: 'KWEME NDOGO', category: 'African Market', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'ky-jelly-mkt', name: 'KY JELLY', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-mkt', name: 'LADY GAY', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-ndogo', name: 'LADY GAY NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-oil-mkt', name: 'LADY GAY OIL', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-oil-ndogo', name: 'LADY GAY OIL NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-powder-mkt', name: 'LADY GAY POWDER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-powder-ndogo', name: 'LADY GAY POWDER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-soap-mkt', name: 'LADY GAY SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-soap-ndogo', name: 'LADY GAY SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-talc-mkt', name: 'LADY GAY TALC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-talc-ndogo', name: 'LADY GAY TALC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-vaseline-mkt', name: 'LADY GAY VASELINE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-vaseline-ndogo', name: 'LADY GAY VASELINE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-wash-mkt', name: 'LADY GAY WASH', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-wash-ndogo', name: 'LADY GAY WASH NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-water-mkt', name: 'LADY GAY WATER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-water-ndogo', name: 'LADY GAY WATER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-white-mkt', name: 'LADY GAY WHITE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-white-ndogo', name: 'LADY GAY WHITE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-yellow-mkt', name: 'LADY GAY YELLOW', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-yellow-ndogo', name: 'LADY GAY YELLOW NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-mkt', name: 'LADY GAY ZINC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-ndogo', name: 'LADY GAY ZINC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-oil-mkt', name: 'LADY GAY ZINC OIL', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-oil-ndogo', name: 'LADY GAY ZINC OIL NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-powder-mkt', name: 'LADY GAY ZINC POWDER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-powder-ndogo', name: 'LADY GAY ZINC POWDER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-soap-mkt', name: 'LADY GAY ZINC SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-soap-ndogo', name: 'LADY GAY ZINC SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-talc-mkt', name: 'LADY GAY ZINC TALC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-talc-ndogo', name: 'LADY GAY ZINC TALC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-vaseline-mkt', name: 'LADY GAY ZINC VASELINE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-vaseline-ndogo', name: 'LADY GAY ZINC VASELINE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-wash-mkt', name: 'LADY GAY ZINC WASH', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-wash-ndogo', name: 'LADY GAY ZINC WASH NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-water-mkt', name: 'LADY GAY ZINC WATER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-water-ndogo', name: 'LADY GAY ZINC WATER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-white-mkt', name: 'LADY GAY ZINC WHITE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-white-ndogo', name: 'LADY GAY ZINC WHITE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-yellow-mkt', name: 'LADY GAY ZINC YELLOW', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-yellow-ndogo', name: 'LADY GAY ZINC YELLOW NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-mkt', name: 'LADY GAY ZINC ZINC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-ndogo', name: 'LADY GAY ZINC ZINC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-oil-mkt', name: 'LADY GAY ZINC ZINC OIL', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-oil-ndogo', name: 'LADY GAY ZINC ZINC OIL NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-powder-mkt', name: 'LADY GAY ZINC ZINC POWDER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-powder-ndogo', name: 'LADY GAY ZINC ZINC POWDER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-soap-mkt', name: 'LADY GAY ZINC ZINC SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-soap-ndogo', name: 'LADY GAY ZINC ZINC SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-talc-mkt', name: 'LADY GAY ZINC ZINC TALC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-talc-ndogo', name: 'LADY GAY ZINC ZINC TALC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-vaseline-mkt', name: 'LADY GAY ZINC ZINC VASELINE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-vaseline-ndogo', name: 'LADY GAY ZINC ZINC VASELINE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-wash-mkt', name: 'LADY GAY ZINC ZINC WASH', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-wash-ndogo', name: 'LADY GAY ZINC ZINC WASH NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-water-mkt', name: 'LADY GAY ZINC ZINC WATER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-water-ndogo', name: 'LADY GAY ZINC ZINC WATER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-white-mkt', name: 'LADY GAY ZINC ZINC WHITE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-white-ndogo', name: 'LADY GAY ZINC ZINC WHITE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-yellow-mkt', name: 'LADY GAY ZINC ZINC YELLOW', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-yellow-ndogo', name: 'LADY GAY ZINC ZINC YELLOW NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-mkt', name: 'LADY GAY ZINC ZINC ZINC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-ndogo', name: 'LADY GAY ZINC ZINC ZINC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-oil-mkt', name: 'LADY GAY ZINC ZINC ZINC OIL', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-oil-ndogo', name: 'LADY GAY ZINC ZINC ZINC OIL NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-powder-mkt', name: 'LADY GAY ZINC ZINC ZINC POWDER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-powder-ndogo', name: 'LADY GAY ZINC ZINC ZINC POWDER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-soap-mkt', name: 'LADY GAY ZINC ZINC ZINC SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-soap-ndogo', name: 'LADY GAY ZINC ZINC ZINC SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-talc-mkt', name: 'LADY GAY ZINC ZINC ZINC TALC', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-talc-ndogo', name: 'LADY GAY ZINC ZINC ZINC TALC NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-vaseline-mkt', name: 'LADY GAY ZINC ZINC ZINC VASELINE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-vaseline-ndogo', name: 'LADY GAY ZINC ZINC ZINC VASELINE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-wash-mkt', name: 'LADY GAY ZINC ZINC ZINC WASH', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-wash-ndogo', name: 'LADY GAY ZINC ZINC ZINC WASH NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-water-mkt', name: 'LADY GAY ZINC ZINC ZINC WATER', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-water-ndogo', name: 'LADY GAY ZINC ZINC ZINC WATER NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-white-mkt', name: 'LADY GAY ZINC ZINC ZINC WHITE', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-white-ndogo', name: 'LADY GAY ZINC ZINC ZINC WHITE NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-yellow-mkt', name: 'LADY GAY ZINC ZINC ZINC YELLOW', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'lady-gay-zinc-zinc-zinc-yellow-ndogo', name: 'LADY GAY ZINC ZINC ZINC YELLOW NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
];
