import { Product } from './types';

export const BUTCHERY_PRODUCTS: Product[] = [
  { id: 'steak', sku: 'STK933355228877', name: 'Steak', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true, description: 'Premium cut of beef, tender and flavorful, perfect for grilling or pan-searing.' },
  { id: 'fillet-nyama', name: 'Fillet nyama', category: 'Butchery', price: 26000, unit: 'kg', isAvailable: true, description: 'The most tender cut of beef, lean and succulent, ideal for a luxury dining experience.' },
  { id: 'kusaga-coty', name: 'Kusaga coty', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true, description: 'Freshly ground premium beef, perfect for burgers, meatballs, or traditional sauces.' },
  { id: 'kawaida-mix', sku: '0', name: 'Kawaida Mix', category: 'Butchery', price: 14000, unit: 'kg', isAvailable: true, description: 'A versatile mix of beef cuts, great for stews and traditional family meals.' },
  { id: 'dog-food-nyama', sku: 'DGN91111666444', name: 'Dog Food (Nyama)', category: 'Butchery', price: 3000, unit: 'kg', isAvailable: true, description: 'Nutritious and fresh meat-based food for your pets, prepared with care.' },
  { id: 'dog-food-kuku', sku: 'DGK9444442222', name: 'Dog food (Kuku)', category: 'Poultry', price: 3000, unit: 'kg', isAvailable: true, description: 'High-protein chicken-based pet food, fresh and healthy.' },
  { id: 'nundu', sku: 'ND9555222111', name: 'Nundu', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true, description: 'Traditional hump meat, rich in fat and flavor, a local delicacy.' },
  { id: 'supu-coty', sku: 'SUP966663222707', name: 'SUPU COTY', category: 'Butchery', price: 5000, unit: 'pc', isAvailable: true, description: 'Rich and hearty traditional soup, prepared fresh daily.' },
  { id: 'maini', name: 'Maini', category: 'Butchery', price: 15000, unit: 'kg', isAvailable: true },
  { id: 'kongoro', name: 'Kongoro', category: 'Butchery', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'mkia', name: 'Mkia', category: 'Butchery', price: 13000, unit: 'pc', isAvailable: true },
  { id: 'utumbo-ngombe', name: "Utumbo (Ng'ombe)", category: 'Butchery', price: 9000, unit: 'kg', isAvailable: true },
  { id: 'ulimi', sku: 'ULM654321', name: 'Ulimi', category: 'Butchery', price: 14000, unit: 'pc', isAvailable: true },
  { id: 'kondoo', name: 'Kondoo', category: 'Butchery', price: 16000, unit: 'kg', isAvailable: true },
  { id: 'mbuzi', name: 'Mbuzi', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true },
  { id: 'asali-coty-1l', name: 'ASALI COTY 1L', category: 'Specialty', price: 15000, unit: '1L', isAvailable: true, description: 'Pure, organic honey harvested from the finest wild blossoms, rich in nutrients and flavor.' },
  { id: 'asali-coty-750', name: 'ASALI COTY 750', category: 'Specialty', price: 13000, unit: '750ml', isAvailable: true, description: 'Premium wild honey in a convenient 750ml size, perfect for daily use.' },
  { id: 'asali-coty-nusu', name: 'ASALI COTY NUSU', category: 'Specialty', price: 8000, unit: '500ml', isAvailable: true, description: 'High-quality organic honey, 500ml bottle, great for gifting or personal use.' },
  { id: 'asali-nyuki-wadogo', name: 'ASALI NYUKI WADOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'asali-pori-1l', name: 'ASALI PORI 1L', category: 'Specialty', price: 15000, unit: '1L', isAvailable: true },
  { id: 'asali-pori-nusu', name: 'ASALI PORI NUSU', category: 'Specialty', price: 8000, unit: '500ml', isAvailable: true },
  { id: 'asali-coty-250', name: 'ASALI COTY 250', category: 'Specialty', price: 6000, unit: '250ml', isAvailable: true },
  { id: 'heaca-chef-spices', name: 'HEACA CHEF SPICES', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'kande-pikwa', name: 'KANDE PIKWA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'maharage', name: 'MAHARAGE', category: 'African Market', price: 5000, unit: 'kg', isAvailable: true },
  { id: 'njugu-mawe', name: 'NJUGU MAWE', category: 'African Market', price: 4000, unit: 'kg', isAvailable: true },
  { id: 'kisamvu', sku: 'KSV92000634', name: 'KISAMVU', category: 'African Market', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'crips', name: 'CRIPS', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mchai-chai', sku: 'MCH926333339', name: 'MCHAI CHAI', category: 'Specialty', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'ubuyu-kashai', name: 'UBUYU KASHAI', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'karanga', name: 'KARANGA', category: 'African Market', price: 4000, unit: 'kg', isAvailable: true },
  { id: 'killian-spicy-5000', name: 'KILLIAN SPICY (5,000)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'killian-spicy', name: 'KILLIAN SPICY', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'killian-spices-black-pepper', name: 'KILLIAN SPICES BLACK PEPPER KOPO', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'killian-white-pepper', name: 'KILLIAN WHITE PEPPER', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'chicken-cubes', name: 'CHICKEN CUBES', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'maggie-beef-cubes', name: 'MAGGIE BEEF CUBES', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mama-sita', name: 'MAMA SITA', category: 'Specialty', price: 13000, unit: 'pc', isAvailable: true },
  { id: 'mwagegi-paprika', name: 'MWAGEGI PAPRIKA', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'mwagegi-spices-350gms', name: 'MWAGEGI SPICES 350GMS', category: 'Specialty', price: 10000, unit: '350g', isAvailable: true },
  { id: 'mwagegi-spices-550gms', name: 'MWAGEGI SPICES 550GMS', category: 'Specialty', price: 12000, unit: '550g', isAvailable: true },
  { id: 'pwani-roast', name: 'PWANI ROAST', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'royco-cubes', name: 'ROYCO CUBES', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'royco-masala', name: 'ROYCO MASALA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'senene-ndogo-kashai', name: 'SENENE NDOGO KASHAI', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'senene-kubwa', name: 'SENENE KUBWA', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'soy-sauce-ndogo', name: 'SOY SAUCE NDOGO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'soy-sauce-kubwa', name: 'SOY SAUCE KUBWA', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'tomato-paste-ndogo', name: 'TOMATO PASTE NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'giya-spices', name: 'GIYA SPICES', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chiesa', name: 'CHIESA', category: 'Specialty', price: 5720, unit: 'pc', isAvailable: true },
  { id: 'beef-cubes-sp', name: 'BEEF CUBES', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'tropical-heat-masala', name: 'TROPICAL HEAT MASALA', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'tea-masala-tropical', name: 'TEA MASALA TROPICAL', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'simba-vinegar', name: 'SIMBA VINEGAR', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'simba-mbili-medium', name: 'SIMBA MBILI (MEDIUM)', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'simba-mbili-kubwa', name: 'SIMBA MBILI (KUBWA)', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'simba-mbili-ndogo', name: 'SIMBA MBILI NDOGO (SIMBA MBILI)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'paprika', name: 'PAPRIKA', category: 'Specialty', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'mustard', name: 'MUSTARD', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'tropical-fish-masala', name: 'TROPICAL FISH MASALA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'new-classic-chill-5000', name: 'NEW CLASSIC CHILL (5,000)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'new-classic-chill-3500', name: 'NEW CLASSIC CHILL (3500)', category: 'Specialty', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'ikoda-cloves-masala', name: 'IKODA CLOVES MASALA', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'almond', name: 'ALMOND', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'nazi-azam', name: 'NAZI AZAM', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'nazi-gsm-kubwa', name: 'NAZI GSM (KUBWA)', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'simba-nazi', name: 'SIMBA NAZI', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'tropical-beef-masala', name: 'TROPICAL BEEF MASALA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chicken-masala-sp', name: 'CHICKEN MASALA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'aromat', name: 'AROMAT', category: 'Specialty', price: 4500, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-3500', name: 'TUNU COCONUT (3500)', category: 'Specialty', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-7000', name: 'TUNU COCONUT (7,000)', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-10000', name: 'TUNU COCONUT (10,000)', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-12000', name: 'TUNU COCONUT (12,000)', category: 'Specialty', price: 12000, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-13000', name: 'TUNU COCONUT (13,000)', category: 'Specialty', price: 13000, unit: 'pc', isAvailable: true },
  { id: 'tunu-coconut-23000', name: 'TUNU COCONUT (23,000)', category: 'Specialty', price: 23000, unit: 'pc', isAvailable: true },
  { id: 'rwaich-coconut-5000', name: 'RWAICH COCONUT (5,000)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'rwaich-coconut-10000', name: 'RWAICH COCONUT (10,000)', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'active-mama-unga-1kg-red', name: 'ACTIVE MAMA UNGA 1KG (RED)', category: 'African Market', price: 8000, unit: 'kg', isAvailable: true },
  { id: 'active-mama-coconut-250ml', name: 'ACTIVE MAMA COCONUT (250ML)', category: 'Specialty', price: 15000, unit: '250ml', isAvailable: true },
  { id: 'active-mama-coconut-120ml', name: 'ACTIVE MAMA COCONUT (120ML)', category: 'Specialty', price: 8000, unit: '120ml', isAvailable: true },
  { id: 'worriers', name: 'WORRIERS', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'habi-paste', name: 'HABI PASTE (KIUNGO CHA MBOGA ) & (GARLIC & GINGER)', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'unga-mbegu-za-maboga', name: 'UNGA MBEGU ZA MABOGA', category: 'African Market', price: 10000, unit: 'kg', isAvailable: true },
  { id: 'unga-ulezi-coty', name: 'UNGA ULEZI COTY', category: 'African Market', price: 10000, unit: 'kg', isAvailable: true },
  { id: 'hopeca', name: 'HOPECA', category: 'African Market', price: 30000, unit: 'kg', isAvailable: true },
  { id: 'charity-unga', sku: 'CYU927883322', name: 'CHARITY UNGA', category: 'African Market', price: 8000, unit: 'kg', isAvailable: true },
  { id: 'coty-lishe', name: 'COTY LISHE', category: 'African Market', price: 10000, unit: 'kg', isAvailable: true },
  { id: 'toto-mix', name: 'TOTO MIX', category: 'African Market', price: 12000, unit: 'kg', isAvailable: true },
  { id: 'mtama-mtamu-toto-mix', name: 'MTAMA MTAMU TOTO MIX', category: 'African Market', price: 10000, unit: 'kg', isAvailable: true },
  { id: 'mercibel-flour', name: 'MERCIBEL FLOUR', category: 'African Market', price: 4000, unit: 'kg', isAvailable: true },
  { id: 'sea-moosi', name: 'SEA MOOSI', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'supa-oats', name: 'SUPA OATS', category: 'Specialty', price: 12000, unit: 'pc', isAvailable: true },
  { id: 'bahati-spices', name: 'BAHATI SPICES', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'sangara-fresh-mwanza', name: 'SANGARA FRESH MWANZA', category: 'Seafood', price: 14000, unit: 'kg', isAvailable: true },
  { id: 'kingfish-fresh', name: 'KINGFISH FRESH', category: 'Seafood', price: 24000, unit: 'kg', isAvailable: true },
  { id: 'sato-fresh-mwanza', name: 'SATO FRESH MWANZA', category: 'Seafood', price: 15000, unit: 'kg', isAvailable: true },
  { id: 'changu-fresh', name: 'CHANGU FRESH', category: 'Seafood', price: 17000, unit: 'kg', isAvailable: true },
  { id: 'sangara-fillet-1kg', sku: 'SNR91144002266884', name: 'SANGARA FILLET 1KG', category: 'Seafood', price: 32000, unit: 'kg', isAvailable: true },
  { id: 'sangara-mkavu-1kg', sku: 'SMV944433227711', name: 'SANGARA MKAVU 1KG', category: 'Seafood', price: 18000, unit: 'kg', isAvailable: true },
  { id: 'interchick-choma-sausage', name: 'INTERCHICK CHOMA SAUSAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'interchick-chicken-vienna', name: 'INTERCHICK CHICKEN VIENNA SAUSAGE', category: 'Processed', price: 7500, unit: 'pack', isAvailable: true },
  { id: 'mix-chicken-mkubwa', name: 'MIX CHICKEN MKUBWA (6500)', category: 'Poultry', price: 6500, unit: 'pc', isAvailable: true },
  { id: 'mix-chicken-mdogo', name: 'MIX CHICKEN MDOGO (3500)', category: 'Poultry', price: 3500, unit: 'pc', isAvailable: true },
  { id: 'frozen-mix', sku: 'FMX92754', name: 'FROZEN MIX', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'coty-boneless-breast', sku: 'CBB902750511', name: 'COTY BONELESS BREAST (14K)', category: 'Poultry', price: 14000, unit: 'kg', isAvailable: true },
  { id: 'coty-boneless-12k', name: 'COTY BONELESS (12K)', category: 'Poultry', price: 13000, unit: 'kg', isAvailable: true },
  { id: 'coty-drumstick', name: 'COTY DRUMSTICK', category: 'Poultry', price: 7500, unit: 'pack', isAvailable: true },
  { id: 'chicken-drumstick-1kg', name: 'CHICKEN DRUMSTICK 1KG', category: 'Poultry', price: 11000, unit: 'kg', isAvailable: true },
  { id: 'coty-legs', name: 'COTY LEGS', category: 'Poultry', price: 7000, unit: 'pack', isAvailable: true },
  { id: 'coty-mgongo', sku: 'CM9276055555', name: 'COTY MGONGO', category: 'Poultry', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'coty-thigh', name: 'COTY THIGH', category: 'Poultry', price: 5500, unit: 'pack', isAvailable: true },
  { id: 'meat-ball-300g', name: 'MEAT BALL 300GRAMS', category: 'Processed', price: 6000, unit: '300g', isAvailable: true },
  { id: 'chicken-ball-300g', name: 'CHICKEN BALL 300GRAMS', category: 'Processed', price: 5500, unit: '300g', isAvailable: true },
  { id: 'burger-beef-300g', name: 'BURGER BEEF 300GRAM', category: 'Processed', price: 8000, unit: '300g', isAvailable: true },
  { id: 'sambusa', name: 'SAMBUSA', category: 'Processed', price: 10000, unit: 'pack', isAvailable: true },
  { id: 'kuku-kienyeji-26k', name: 'KUKU KIENYEJI (26K)', category: 'Poultry', price: 26000, unit: 'pc', isAvailable: true },
  { id: 'kuku-kienyeji-22k', name: 'KUKU KIENYEJI (22K)', category: 'Poultry', price: 23000, unit: 'pc', isAvailable: true },
  { id: 'kuku-kisasa-8k', name: 'KUKU KISASA (8k)', category: 'Poultry', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'kuku-chotara', name: 'KUKU CHOTARA', category: 'Poultry', price: 23000, unit: 'pc', isAvailable: true },
  { id: 'kuku-wakubwa-1-3kg', name: 'KUKU WAKUBWA (1.3 KG)', category: 'Poultry', price: 12000, unit: 'pc', isAvailable: true },
  { id: 'coty-wings', name: 'COTY WINGS', category: 'Poultry', price: 13000, unit: 'kg', isAvailable: true },
  { id: 'coty-firigisi', name: 'COTY FIRIGISI', category: 'Poultry', price: 8500, unit: 'kg', isAvailable: true },
  { id: 'kuku-kisasa-1-5-1-6kg', name: 'KUKU KISASA (1.5 KG & 1.6KG)', category: 'Poultry', price: 14000, unit: 'pc', isAvailable: true },
  { id: 'kuku-kisasa-1kg', sku: 'KKS99092788', name: 'KUKU KISASA (1KG)', category: 'Poultry', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'kuku-kisasa-1-4kg', sku: 'KKS911211790', name: 'KUKU KISASA (1.4 KG)', category: 'Poultry', price: 13000, unit: 'pc', isAvailable: true },
  { id: 'lollypop-alpha-1kg', name: 'LOLLYPOP ALPHA 1KG', category: 'Poultry', price: 7000, unit: 'kg', isAvailable: true },
  { id: 'alpha-changu-1kg', name: 'ALPHA CHANGU 1KG', category: 'Seafood', price: 18000, unit: 'kg', isAvailable: true },
  { id: 'alpha-drummets-1kg', name: 'ALPHA DRUMMETS 1KG', category: 'Poultry', price: 6000, unit: 'kg', isAvailable: true },
  { id: 'alpha-kibua-1kg', name: 'ALPHA KIBUA 1KG', category: 'Seafood', price: 16000, unit: 'kg', isAvailable: true },
  { id: 'alpha-kingfish-1kg', name: 'ALPHA KINGFISH 1KG', category: 'Seafood', price: 25000, unit: 'kg', isAvailable: true },
  { id: 'alpha-pup-small', name: 'ALPHA PUP SMALL', category: 'Seafood', price: 19000, unit: 'kg', isAvailable: true },
  { id: 'alpha-pud-large', name: 'ALPHA PUD LARGE', category: 'Seafood', price: 30000, unit: 'kg', isAvailable: true },
  { id: 'alpha-pud-medium', name: 'ALPHA PUD MEDIUM', category: 'Seafood', price: 28000, unit: 'kg', isAvailable: true },
  { id: 'dagaa-kashai-kubwa', name: 'DAGAA KASHAI KUBWA', category: 'Seafood', price: 16000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-sacova-ndogo', name: 'DAGAA SACOVA NDOGO', category: 'Seafood', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-mambola-ndogo', name: 'DAGAA MAMBOLA NDOGO', category: 'Seafood', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-sacova-kubwa', name: 'DAGAA SACOVA KUBWA', category: 'Seafood', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-chichi', name: 'DAGAA CHICHI', category: 'Seafood', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-kigoma-nusu', name: 'DAGAA KIGOMA NUSU', category: 'Seafood', price: 28000, unit: '500g', isAvailable: true },
  { id: 'dagaa-kashai-kati', name: 'DAGAA KASHAI KATI', category: 'Seafood', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-kashai-ndogo', name: 'DAGAA KASHAI NDOGO', category: 'Seafood', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'dagaa-kashai-8k', sku: 'DK92826622662', name: 'DAGAA KASHAI (8K)', category: 'Seafood', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'asas-mtindi-1ltr', name: 'ASAS MTINDI 1LTR', category: 'Specialty', price: 5000, unit: '1L', isAvailable: true },
  { id: 'asas-fresh-500ml', name: 'ASAS FRESH (500 MLS)', category: 'Specialty', price: 2000, unit: '500ml', isAvailable: true },
  { id: 'asas-packet-mtindi-500ml', name: 'ASAS PACKET MTINDI (500 ML)', category: 'Specialty', price: 2000, unit: '500ml', isAvailable: true },
  { id: 'asas-yoghurt-ndogo', name: 'ASAS YOGHURT NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'asas-yoghurt-kubwa', sku: 'YK92836', name: 'ASAS YOGHURT KUBWA', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'asas-box-1ltr', name: 'ASAS BOX 1LTR', category: 'Specialty', price: 5000, unit: '1L', isAvailable: true },
  { id: 'asas-mtindi-3ltr', name: 'ASAS MTINDI 3LTR', category: 'Specialty', price: 11000, unit: '3L', isAvailable: true },
  { id: 'tanga-mtindi-3ltr', name: 'TANGA MTINDI 3LTR', category: 'Specialty', price: 12000, unit: '3L', isAvailable: true },
  { id: 'tanga-mtindi-packet', name: 'TANGA MTINDI PACKET', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'tanga-fresh-uht-450ml', name: 'TANGA FRESH UHT (450 ML)', category: 'Specialty', price: 2000, unit: '450ml', isAvailable: true },
  { id: 'tanga-salted-butter', name: 'TANGA SALTED BUTTER', category: 'Specialty', price: 18000, unit: 'pc', isAvailable: true },
  { id: 'butter-lato-ndogo', name: 'BUTTER LATO NDOGO', category: 'Specialty', price: 12000, unit: 'pc', isAvailable: true },
  { id: 'butter-lato-kubwa', name: 'BUTTER LATO KUBWA', category: 'Specialty', price: 21000, unit: 'pc', isAvailable: true },
  { id: 'mozarella-cheese-jaiva-250ml', name: 'MOZARELLA CHEESE JAIVA (250ML)', category: 'Specialty', price: 8000, unit: '250ml', isAvailable: true },
  { id: 'mozarella-cheese-jaiva-500g', name: 'MOZARELLA CHEESE JAIVA (500 g)', category: 'Specialty', price: 10000, unit: '500g', isAvailable: true },
  { id: 'mozarella-cheese-jaiva-1kg', name: 'MOZARELLA CHEESE JAIVA (1KG)', category: 'Specialty', price: 20000, unit: 'kg', isAvailable: true },
  { id: 'mozarella-kanova', name: 'MOZARELLA KANOVA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mayai-kienyeji', sku: 'MKNY92868', name: 'MAYAI KIENYEJI', category: 'Poultry', price: 21000, unit: 'tray', isAvailable: true },
  { id: 'mayai-kisasa-trey', sku: 'MKS37896', name: 'MAYAI KISASA TREY', category: 'Poultry', price: 11000, unit: 'tray', isAvailable: true },
  { id: 'shambani-mtindi-3l', name: 'SHAMBANI MTINDI 3L', category: 'Specialty', price: 13000, unit: '3L', isAvailable: true },
  { id: 'shambani-mtindi-packet', name: 'SHAMBANI MTINDI PACKET', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'shambani-mtindi-5l', name: 'SHAMBANI MTINDI 5L', category: 'Specialty', price: 19000, unit: '5L', isAvailable: true },
  { id: 'shambani-fresh-3l', name: 'SHAMBANI FRESH 3L', category: 'Specialty', price: 13000, unit: '3L', isAvailable: true },
  { id: 'shambani-fresh-5l', name: 'SHAMBANI FRESH 5L', category: 'Specialty', price: 19000, unit: '5L', isAvailable: true },
  { id: 'shambani-mtindi-1l', name: 'SHAMBANI MTINDI 1L', category: 'Specialty', price: 5000, unit: '1L', isAvailable: true },
  { id: 'chicken-stirfly', name: 'CHICKEN STIRFLY', category: 'Poultry', price: 12500, unit: 'kg', isAvailable: true },
  { id: 'chicken-burger', name: 'CHICKEN BURGER', category: 'Processed', price: 8000, unit: 'pack', isAvailable: true },
  { id: 'coty-chicken-vienna', name: 'COTY CHICKEN VIENNA SAUSAGE', category: 'Processed', price: 8000, unit: 'pack', isAvailable: true },
  { id: 'sausage-vienna-kenya', name: 'SAUSAGE VIENNA KENYA', category: 'Processed', price: 10000, unit: 'pack', isAvailable: true },
  { id: 'coty-russian-sausage-500g', name: 'COTY RUSSIAN SAUSAGE (500 GM)', category: 'Processed', price: 10000, unit: '500g', isAvailable: true },
  { id: 'safari-chill-bites', name: 'SAFARI CHILL BITES', category: 'Processed', price: 6000, unit: 'pack', isAvailable: true },
  { id: 'coty-smoked-plain-sausage', name: 'COTY SMOKED PLAIN SAUASAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'farmers-choice-spicy-russian', name: "FARMER'S CHOICE SPICY / RUSSIAN SPICY SAUSAGE", category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'happy-russian-sausage', name: 'HAPPY RUSSIAN SAUSAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'happy-beef-vienna', name: 'HAPPY BEEF VIENNA', category: 'Processed', price: 9000, unit: 'pack', isAvailable: true },
  { id: 'alpha-russian-sausage', name: 'ALPHA RUSSIAN SAUASAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'farmers-choice-choma-sausage', name: "FARMER'S CHOICE CHOMA SAUSAGE", category: 'Processed', price: 33000, unit: 'pack', isAvailable: true },
  { id: 'beef-bacon', name: 'BEEF BECON', category: 'Processed', price: 8000, unit: 'pack', isAvailable: true },
  { id: 'coty-breakfast-beef-sausage', name: 'COTY BREAKFAST BEEF SAUSAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'coty-beef-vienna-sausage', name: 'COTY BEEF VIENNA SAUSAGE', category: 'Processed', price: 8000, unit: 'pack', isAvailable: true },
  { id: 'coty-smoked-chill-beef-sausage', name: 'COTY SMOKED CHILL BEEF SAUSAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'beef-borrowers-sausage', name: 'BEEF BORROWERS SAUSAGE', category: 'Processed', price: 12000, unit: 'pack', isAvailable: true },
  { id: 'salami-kubwa-sausage', name: 'SALAMI KUBWA SAUSAGE', category: 'Processed', price: 28000, unit: 'pc', isAvailable: true },
  { id: 'salami-ndogo-sausage', name: 'SALAMI NDOGO SAUSAGE', category: 'Processed', price: 5500, unit: 'pc', isAvailable: true },
  { id: 'mayai-kisasa-trey-2', name: 'MAYAI KISASA TREY', category: 'Poultry', price: 12000, unit: 'tray', isAvailable: true },
  { id: 'habi-garlic-paste-only', name: 'HABI (GARLIC PASTE ONLY)', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'habi-choco-spread', name: 'HABI CHOCO SPREAD', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'mwagegi-fish-paste', name: 'MWAGEGI FISH PASTE', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mwagegi-coriander-pepper', name: 'MWAGEGI (CORIANDER PEPPER)', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'chesca-fish-species', name: 'CHESCA FISH SPECIES', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-coriander', name: 'CHESCA CORIANDER', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-cardamon', name: 'CHESCA CARDAMON', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'supa-lishe-360-1kg', name: 'SUPA LISHE 360 (1KG)', category: 'African Market', price: 12000, unit: 'kg', isAvailable: true },
  { id: 'mwagegi-cayenne-pepper', name: 'MWAGEGI CAYENNE PEPPER', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-chicken', name: 'CHESCA CHICKEN', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-cumin', name: 'CHESCA CUMIN', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-cloves', name: 'CHESCA CLOVES', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-ginger', name: 'CHESCA GINGER', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-garlic', name: 'CHESCA GARLIC', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'chesca-tumeric', name: 'CHESCA TUMERIC', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mbilimbi', name: 'MBILIMBI', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'pwani-samaki', name: 'PWANI SAMAKI', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'magic-jikoni', name: 'MAGIC JIKONI', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'steak-maini-species', name: 'STEAK &MAINI SPECIES', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'yummy-pilau', name: 'YUMMY PILAU', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'nyama-choma-species', name: 'NYAMA CHOMA SPECIES', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'active-mama-unga-1kg-green', name: 'ACTIVE MAMA UNGA 1KG (GREEN)', category: 'African Market', price: 8000, unit: 'kg', isAvailable: true },
  { id: 'ikoda-ginger-species', name: 'IKODA GINGER SPECIES', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'ikoda-spices-2', name: 'IKODA SPICES', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'rosella', sku: 'RSL9321105768', name: 'ROSELLA', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'kenya-farmers-choice-beef-viennas', name: "KENYA FARMER'S CHOICE BEEF VIENNAS", category: 'Processed', price: 10000, unit: 'pack', isAvailable: true },
  { id: 'tanga-unsalted-butter', name: 'TANGA UNSALTED BUTTER', category: 'Specialty', price: 18000, unit: 'pc', isAvailable: true },
  { id: 'mozzarella-tanga-cheese', name: 'MOZZARELLA TANGA CHEESE', category: 'Specialty', price: 17000, unit: 'pc', isAvailable: true },
  { id: 'maries-choco-spices', name: 'MARIES CHOCO SPICES', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'stir-fly-beef', name: 'STIR FLY BEEF', category: 'Butchery', price: 8500, unit: 'kg', isAvailable: true },
  { id: 'kuku-1-2kg', name: 'KUKU (1.2KG)', category: 'Poultry', price: 11000, unit: 'pc', isAvailable: true },
  { id: 'jembe', name: 'Jembe', category: 'Butchery', price: 13000, unit: 'kg', isAvailable: true },
  { id: 'alpha-frozen-fillet', name: 'ALPHA FROZEN FILLET', category: 'Seafood', price: 32000, unit: 'kg', isAvailable: true },
  { id: 'coty-beef-choma', name: 'COTY BEEF CHOMA', category: 'Butchery', price: 10000, unit: 'kg', isAvailable: true },
  { id: 'kuku-kisasa-0-9-1kg', name: 'KUKU KISASA 0.9+1KG', category: 'Poultry', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'coty-vienna-50-pc', name: 'COTY VIENNA 50 PC', category: 'Processed', price: 22000, unit: 'pack', isAvailable: true },
  { id: 'maini-plain-figo', name: 'MAINI PLAIN/FIGO', category: 'Butchery', price: 16000, unit: 'kg', isAvailable: true },
  { id: 'hopeca-1kg', name: 'HOPECA 1KG', category: 'African Market', price: 30000, unit: 'kg', isAvailable: true },
  { id: 'mercibel-unga-muhogo-1kg', name: 'MERCIBEL (UNGA HALISI WA MUHOGO) 1KG', category: 'African Market', price: 4000, unit: 'kg', isAvailable: true },
  { id: 'turmeric-powder-100g', name: 'TURMERIC POWDER 100G', category: 'Specialty', price: 7000, unit: '100g', isAvailable: true },
  { id: 'meries-spices-choco-spread', name: 'MERIES SPICES CHOCO SPREAD', category: 'Specialty', price: 9000, unit: 'pc', isAvailable: true },
  { id: 'azam-coconut-cream', name: 'AZAM COCONUT CREAM(AZAM NAZI)', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'pwani-roast-2', name: 'PWANI ROAST', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'kuku-choma', name: 'KUKU CHOMA', category: 'Poultry', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'salbena-honey', name: 'SALBENA HONEY', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mwagegi-garlic-ginger', name: 'MWAGEGI GARLIC&GINGER', category: 'Specialty', price: 12000, unit: 'pc', isAvailable: true },
  { id: 'asas-yoghurt-pineapple-ndogo', name: 'ASAS YOGHURT PINEAPPLE FLAVOUR NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'asas-yoghurt-vanilla-ndogo', name: 'ASAS YOGHURT VANILLA FLAVOUR NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'kuku-wa-kisasa', name: 'KUKU WA KISASA', category: 'Poultry', price: 7500, unit: 'pc', isAvailable: true },
  { id: 'paprika-spice-100g', name: 'PAPRIKA SPICE 100G', category: 'Specialty', price: 5000, unit: '100g', isAvailable: true },
  { id: 'cinnamon-powder', name: 'CINNAMON POWDER(SPICE SEASONING)', category: 'Specialty', price: 7000, unit: 'pc', isAvailable: true },
  { id: 'garam-masala', name: 'GARAM MASALA(SPICE SEASONING)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'oregano-powder', name: 'OREGANO POWDER (NATURAL SPICES)', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'tea-masala-seasoning', name: 'TEA MASALA(SPICE SEASONING)', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'black-pepper-natural', name: 'BLACK PEPPER(NATURAL SPICES)', category: 'Specialty', price: 8000, unit: 'pc', isAvailable: true },
  { id: 'vanilla', name: 'VANILLA', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'sangara-bila-kichwa', name: 'SANGARA BILA KICHWA', category: 'Seafood', price: 18000, unit: 'kg', isAvailable: true },
  { id: 'vichwa-vya-sangara', name: 'VICHWA VYA SANGARA', category: 'Seafood', price: 7000, unit: 'kg', isAvailable: true },
  { id: 'new-classic-lemon-chill', name: 'NEW CLASSIC LEMON CHILL', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'kawaida-mix-2', name: 'Kawaida Mix', category: 'Butchery', price: 14000, unit: 'kg', isAvailable: true },
  { id: 'kuku-1-1', name: 'KUKU 1.1', category: 'Poultry', price: 8500, unit: 'pc', isAvailable: true },
  { id: 'beef-biltong', name: 'BEEF BILTONG', category: 'Processed', price: 10000, unit: 'pack', isAvailable: true },
  { id: 'beef-snacks', name: 'BEEF SNACKS', category: 'Processed', price: 3000, unit: 'pack', isAvailable: true },
  { id: 'azamu-nazi', name: 'AZAMU NAZI', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'chotara-mkubwa', name: 'CHOTARA MKUBWA', category: 'Poultry', price: 25000, unit: 'pc', isAvailable: true },
];
