import { Product } from './types';

export const MARKET_PRODUCTS_7: Product[] = [
  { id: 'ring-mkt', name: 'RING', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'ring-ndogo-mkt', name: 'RING NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rinso-mkt', name: 'RINSO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'rinso-ndogo-mkt', name: 'RINSO NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rio-mkt', name: 'RIO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rio-ndogo-mkt', name: 'RIO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rise-mkt', name: 'RISE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rise-ndogo-mkt', name: 'RISE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rit-mkt', name: 'RIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rit-ndogo-mkt', name: 'RIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ritz-mkt', name: 'RITZ', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'ritz-ndogo-mkt', name: 'RITZ NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'river-mkt', name: 'RIVER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'river-ndogo-mkt', name: 'RIVER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'roast-mkt', name: 'ROAST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'roast-ndogo-mkt', name: 'ROAST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rob-mkt', name: 'ROB', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rob-ndogo-mkt', name: 'ROB NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'robin-mkt', name: 'ROBIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'robin-ndogo-mkt', name: 'ROBIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rock-mkt', name: 'ROCK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rock-ndogo-mkt', name: 'ROCK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rod-mkt', name: 'ROD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rod-ndogo-mkt', name: 'ROD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rol-mkt', name: 'ROL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rol-ndogo-mkt', name: 'ROL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'roll-mkt', name: 'ROLL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'roll-ndogo-mkt', name: 'ROLL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rom-mkt', name: 'ROM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rom-ndogo-mkt', name: 'ROM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'roma-mkt', name: 'ROMA', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'roma-ndogo-mkt', name: 'ROMA NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ron-mkt', name: 'RON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ron-ndogo-mkt', name: 'RON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'roof-mkt', name: 'ROOF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'roof-ndogo-mkt', name: 'ROOF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'root-mkt', name: 'ROOT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'root-ndogo-mkt', name: 'ROOT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rope-mkt', name: 'ROPE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'rope-ndogo-mkt', name: 'ROPE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rose-mkt', name: 'ROSE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'rose-ndogo-mkt', name: 'ROSE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'rot-mkt', name: 'ROT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rot-ndogo-mkt', name: 'ROT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rough-mkt', name: 'ROUGH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rough-ndogo-mkt', name: 'ROUGH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'round-mkt', name: 'ROUND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'round-ndogo-mkt', name: 'ROUND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'row-mkt', name: 'ROW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'row-ndogo-mkt', name: 'ROW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'roy-mkt', name: 'ROY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'roy-ndogo-mkt', name: 'ROY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'royal-mkt', name: 'ROYAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'royal-ndogo-mkt', name: 'ROYAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'royco-mkt', name: 'ROYCO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'royco-ndogo-mkt', name: 'ROYCO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rub-mkt', name: 'RUB', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rub-ndogo-mkt', name: 'RUB NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ruby-mkt', name: 'RUBY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ruby-ndogo-mkt', name: 'RUBY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rug-mkt', name: 'RUG', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'rug-ndogo-mkt', name: 'RUG NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'rule-mkt', name: 'RULE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rule-ndogo-mkt', name: 'RULE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rum-mkt', name: 'RUM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rum-ndogo-mkt', name: 'RUM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'run-mkt', name: 'RUN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'run-ndogo-mkt', name: 'RUN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rush-mkt', name: 'RUSH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rush-ndogo-mkt', name: 'RUSH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rust-mkt', name: 'RUST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rust-ndogo-mkt', name: 'RUST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'rye-mkt', name: 'RYE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'rye-ndogo-mkt', name: 'RYE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 's-mkt', name: 'S', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 's-ndogo-mkt', name: 'S NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sack-mkt', name: 'SACK', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'sack-ndogo-mkt', name: 'SACK NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'sad-mkt', name: 'SAD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sad-ndogo-mkt', name: 'SAD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'safe-mkt', name: 'SAFE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'safe-ndogo-mkt', name: 'SAFE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'safety-mkt', name: 'SAFETY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'safety-ndogo-mkt', name: 'SAFETY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'saffron-mkt', name: 'SAFFRON', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'saffron-ndogo-mkt', name: 'SAFFRON NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'sage-mkt', name: 'SAGE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'sage-ndogo-mkt', name: 'SAGE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'sail-mkt', name: 'SAIL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sail-ndogo-mkt', name: 'SAIL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'saint-mkt', name: 'SAINT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'saint-ndogo-mkt', name: 'SAINT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'salad-mkt', name: 'SALAD', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'salad-ndogo-mkt', name: 'SALAD NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'salt-mkt', name: 'SALT', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'salt-ndogo-mkt', name: 'SALT NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sam-mkt', name: 'SAM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sam-ndogo-mkt', name: 'SAM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sand-mkt', name: 'SAND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sand-ndogo-mkt', name: 'SAND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
