import { Product } from './types';

export const MARKET_PRODUCTS_8: Product[] = [
  { id: 'sardine-mkt', name: 'SARDINE', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'sardine-ndogo-mkt', name: 'SARDINE NDOGO', category: 'Specialty', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'sat-mkt', name: 'SAT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sat-ndogo-mkt', name: 'SAT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sauce-mkt', name: 'SAUCE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'sauce-ndogo-mkt', name: 'SAUCE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'save-mkt', name: 'SAVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'save-ndogo-mkt', name: 'SAVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'saw-mkt', name: 'SAW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'saw-ndogo-mkt', name: 'SAW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'say-mkt', name: 'SAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'say-ndogo-mkt', name: 'SAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'scale-mkt', name: 'SCALE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'scale-ndogo-mkt', name: 'SCALE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'school-mkt', name: 'SCHOOL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'school-ndogo-mkt', name: 'SCHOOL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'scoop-mkt', name: 'SCOOP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'scoop-ndogo-mkt', name: 'SCOOP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'score-mkt', name: 'SCORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'score-ndogo-mkt', name: 'SCORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'scotch-mkt', name: 'SCOTCH', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'scotch-ndogo-mkt', name: 'SCOTCH NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'scour-mkt', name: 'SCOUR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'scour-ndogo-mkt', name: 'SCOUR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'scrap-mkt', name: 'SCRAP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'scrap-ndogo-mkt', name: 'SCRAP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'screen-mkt', name: 'SCREEN', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'screen-ndogo-mkt', name: 'SCREEN NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'screw-mkt', name: 'SCREW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'screw-ndogo-mkt', name: 'SCREW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'scrub-mkt', name: 'SCRUB', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'scrub-ndogo-mkt', name: 'SCRUB NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sea-mkt', name: 'SEA', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sea-ndogo-mkt', name: 'SEA NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seal-mkt', name: 'SEAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seal-ndogo-mkt', name: 'SEAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'search-mkt', name: 'SEARCH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'search-ndogo-mkt', name: 'SEARCH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'season-mkt', name: 'SEASON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'season-ndogo-mkt', name: 'SEASON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seat-mkt', name: 'SEAT', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'seat-ndogo-mkt', name: 'SEAT NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'second-mkt', name: 'SECOND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'second-ndogo-mkt', name: 'SECOND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'secret-mkt', name: 'SECRET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'secret-ndogo-mkt', name: 'SECRET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'section-mkt', name: 'SECTION', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'section-ndogo-mkt', name: 'SECTION NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seed-mkt', name: 'SEED', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'seed-ndogo-mkt', name: 'SEED NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seek-mkt', name: 'SEEK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seek-ndogo-mkt', name: 'SEEK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seem-mkt', name: 'SEEM', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seem-ndogo-mkt', name: 'SEEM NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seen-mkt', name: 'SEEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seen-ndogo-mkt', name: 'SEEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'self-mkt', name: 'SELF', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'self-ndogo-mkt', name: 'SELF NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sell-mkt', name: 'SELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sell-ndogo-mkt', name: 'SELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'send-mkt', name: 'SEND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'send-ndogo-mkt', name: 'SEND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'senior-mkt', name: 'SENIOR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'senior-ndogo-mkt', name: 'SENIOR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sense-mkt', name: 'SENSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sense-ndogo-mkt', name: 'SENSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sent-mkt', name: 'SENT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sent-ndogo-mkt', name: 'SENT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sentence-mkt', name: 'SENTENCE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sentence-ndogo-mkt', name: 'SENTENCE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'separate-mkt', name: 'SEPARATE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'separate-ndogo-mkt', name: 'SEPARATE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'serve-mkt', name: 'SERVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'serve-ndogo-mkt', name: 'SERVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'service-mkt', name: 'SERVICE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'service-ndogo-mkt', name: 'SERVICE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'set-mkt', name: 'SET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'set-ndogo-mkt', name: 'SET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'seven-mkt', name: 'SEVEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'seven-ndogo-mkt', name: 'SEVEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'several-mkt', name: 'SEVERAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'several-ndogo-mkt', name: 'SEVERAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shade-mkt', name: 'SHADE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shade-ndogo-mkt', name: 'SHADE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shadow-mkt', name: 'SHADOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shadow-ndogo-mkt', name: 'SHADOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shake-mkt', name: 'SHAKE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shake-ndogo-mkt', name: 'SHAKE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shall-mkt', name: 'SHALL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shall-ndogo-mkt', name: 'SHALL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shampoo-mkt', name: 'SHAMPOO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'shampoo-ndogo-mkt', name: 'SHAMPOO NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'shape-mkt', name: 'SHAPE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shape-ndogo-mkt', name: 'SHAPE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'share-mkt', name: 'SHARE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'share-ndogo-mkt', name: 'SHARE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sharp-mkt', name: 'SHARP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sharp-ndogo-mkt', name: 'SHARP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'she-mkt', name: 'SHE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'she-ndogo-mkt', name: 'SHE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
