import { Product } from './types';

export const MARKET_PRODUCTS_10: Product[] = [
  { id: 'solar-mkt', name: 'SOLAR', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'solar-ndogo-mkt', name: 'SOLAR NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'sold-mkt', name: 'SOLD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sold-ndogo-mkt', name: 'SOLD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soldier-mkt', name: 'SOLDIER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soldier-ndogo-mkt', name: 'SOLDIER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'solid-mkt', name: 'SOLID', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'solid-ndogo-mkt', name: 'SOLID NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'solution-mkt', name: 'SOLUTION', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'solution-ndogo-mkt', name: 'SOLUTION NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'solve-mkt', name: 'SOLVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'solve-ndogo-mkt', name: 'SOLVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'some-mkt', name: 'SOME', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'some-ndogo-mkt', name: 'SOME NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'somebody-mkt', name: 'SOMEBODY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'somebody-ndogo-mkt', name: 'SOMEBODY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'somehow-mkt', name: 'SOMEHOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'somehow-ndogo-mkt', name: 'SOMEHOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'someone-mkt', name: 'SOMEONE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'someone-ndogo-mkt', name: 'SOMEONE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'something-mkt', name: 'SOMETHING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'something-ndogo-mkt', name: 'SOMETHING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sometime-mkt', name: 'SOMETIME', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sometime-ndogo-mkt', name: 'SOMETIME NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'somewhere-mkt', name: 'SOMEWHERE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'somewhere-ndogo-mkt', name: 'SOMEWHERE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'son-mkt', name: 'SON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'son-ndogo-mkt', name: 'SON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'song-mkt', name: 'SONG', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'song-ndogo-mkt', name: 'SONG NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soon-mkt', name: 'SOON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soon-ndogo-mkt', name: 'SOON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soot-mkt', name: 'SOOT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soot-ndogo-mkt', name: 'SOOT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sore-mkt', name: 'SORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sore-ndogo-mkt', name: 'SORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sorry-mkt', name: 'SORRY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sorry-ndogo-mkt', name: 'SORRY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sort-mkt', name: 'SORT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sort-ndogo-mkt', name: 'SORT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soul-mkt', name: 'SOUL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soul-ndogo-mkt', name: 'SOUL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sound-mkt', name: 'SOUND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sound-ndogo-mkt', name: 'SOUND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soup-mkt', name: 'SOUP', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'soup-ndogo-mkt', name: 'SOUP NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'sour-mkt', name: 'SOUR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sour-ndogo-mkt', name: 'SOUR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'source-mkt', name: 'SOURCE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'source-ndogo-mkt', name: 'SOURCE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'south-mkt', name: 'SOUTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'south-ndogo-mkt', name: 'SOUTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'southern-mkt', name: 'SOUTHERN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'southern-ndogo-mkt', name: 'SOUTHERN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'space-mkt', name: 'SPACE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'space-ndogo-mkt', name: 'SPACE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spade-mkt', name: 'SPADE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'spade-ndogo-mkt', name: 'SPADE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'speak-mkt', name: 'SPEAK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'speak-ndogo-mkt', name: 'SPEAK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'special-mkt', name: 'SPECIAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'special-ndogo-mkt', name: 'SPECIAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'speech-mkt', name: 'SPEECH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'speech-ndogo-mkt', name: 'SPEECH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'speed-mkt', name: 'SPEED', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'speed-ndogo-mkt', name: 'SPEED NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spell-mkt', name: 'SPELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spell-ndogo-mkt', name: 'SPELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spend-mkt', name: 'SPEND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spend-ndogo-mkt', name: 'SPEND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spent-mkt', name: 'SPENT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spent-ndogo-mkt', name: 'SPENT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spider-mkt', name: 'SPIDER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spider-ndogo-mkt', name: 'SPIDER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spin-mkt', name: 'SPIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spin-ndogo-mkt', name: 'SPIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spirit-mkt', name: 'SPIRIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spirit-ndogo-mkt', name: 'SPIRIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spite-mkt', name: 'SPITE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spite-ndogo-mkt', name: 'SPITE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'split-mkt', name: 'SPLIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'split-ndogo-mkt', name: 'SPLIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spoken-mkt', name: 'SPOKEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spoken-ndogo-mkt', name: 'SPOKEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sport-mkt', name: 'SPORT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sport-ndogo-mkt', name: 'SPORT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spot-mkt', name: 'SPOT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spot-ndogo-mkt', name: 'SPOT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spread-mkt', name: 'SPREAD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spread-ndogo-mkt', name: 'SPREAD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'spring-mkt', name: 'SPRING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'spring-ndogo-mkt', name: 'SPRING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'square-mkt', name: 'SQUARE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'square-ndogo-mkt', name: 'SQUARE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stage-mkt', name: 'STAGE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stage-ndogo-mkt', name: 'STAGE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stairs-mkt', name: 'STAIRS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stairs-ndogo-mkt', name: 'STAIRS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'stand-mkt', name: 'STAND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'stand-ndogo-mkt', name: 'STAND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
