import { Product } from './types';

export const MARKET_PRODUCTS_13: Product[] = [
  { id: 'then-mkt', name: 'THEN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'then-ndogo-mkt', name: 'THEN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'theory-mkt', name: 'THEORY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'theory-ndogo-mkt', name: 'THEORY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'there-mkt', name: 'THERE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'there-ndogo-mkt', name: 'THERE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'therefore-mkt', name: 'THEREFORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'therefore-ndogo-mkt', name: 'THEREFORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'these-mkt', name: 'THESE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'these-ndogo-mkt', name: 'THESE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'they-mkt', name: 'THEY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'they-ndogo-mkt', name: 'THEY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thick-mkt', name: 'THICK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thick-ndogo-mkt', name: 'THICK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thin-mkt', name: 'THIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thin-ndogo-mkt', name: 'THIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thing-mkt', name: 'THING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thing-ndogo-mkt', name: 'THING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'think-mkt', name: 'THINK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'think-ndogo-mkt', name: 'THINK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'third-mkt', name: 'THIRD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'third-ndogo-mkt', name: 'THIRD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'this-mkt', name: 'THIS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'this-ndogo-mkt', name: 'THIS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'those-mkt', name: 'THOSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'those-ndogo-mkt', name: 'THOSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'though-mkt', name: 'THOUGH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'though-ndogo-mkt', name: 'THOUGH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thought-mkt', name: 'THOUGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thought-ndogo-mkt', name: 'THOUGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thousand-mkt', name: 'THOUSAND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thousand-ndogo-mkt', name: 'THOUSAND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thread-mkt', name: 'THREAD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thread-ndogo-mkt', name: 'THREAD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'three-mkt', name: 'THREE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'three-ndogo-mkt', name: 'THREE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'threw-mkt', name: 'THREW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'threw-ndogo-mkt', name: 'THREW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'throat-mkt', name: 'THROAT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'throat-ndogo-mkt', name: 'THROAT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'through-mkt', name: 'THROUGH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'through-ndogo-mkt', name: 'THROUGH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'throughout-mkt', name: 'THROUGHOUT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'throughout-ndogo-mkt', name: 'THROUGHOUT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'throw-mkt', name: 'THROW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'throw-ndogo-mkt', name: 'THROW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thrown-mkt', name: 'THROWN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thrown-ndogo-mkt', name: 'THROWN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thumb-mkt', name: 'THUMB', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thumb-ndogo-mkt', name: 'THUMB NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thunder-mkt', name: 'THUNDER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thunder-ndogo-mkt', name: 'THUNDER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'thus-mkt', name: 'THUS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'thus-ndogo-mkt', name: 'THUS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tick-mkt', name: 'TICK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tick-ndogo-mkt', name: 'TICK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ticket-mkt', name: 'TICKET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ticket-ndogo-mkt', name: 'TICKET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tide-mkt', name: 'TIDE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'tide-ndogo-mkt', name: 'TIDE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'tie-mkt', name: 'TIE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tie-ndogo-mkt', name: 'TIE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tight-mkt', name: 'TIGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tight-ndogo-mkt', name: 'TIGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tile-mkt', name: 'TILE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tile-ndogo-mkt', name: 'TILE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'till-mkt', name: 'TILL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'till-ndogo-mkt', name: 'TILL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'time-mkt', name: 'TIME', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'time-ndogo-mkt', name: 'TIME NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tin-mkt', name: 'TIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tin-ndogo-mkt', name: 'TIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tiny-mkt', name: 'TINY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tiny-ndogo-mkt', name: 'TINY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tip-mkt', name: 'TIP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tip-ndogo-mkt', name: 'TIP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tire-mkt', name: 'TIRE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'tire-ndogo-mkt', name: 'TIRE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'tired-mkt', name: 'TIRED', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tired-ndogo-mkt', name: 'TIRED NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tissue-mkt', name: 'TISSUE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tissue-ndogo-mkt', name: 'TISSUE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'title-mkt', name: 'TITLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'title-ndogo-mkt', name: 'TITLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'to-mkt', name: 'TO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'to-ndogo-mkt', name: 'TO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tobacco-mkt', name: 'TOBACCO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'tobacco-ndogo-mkt', name: 'TOBACCO NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'today-mkt', name: 'TODAY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'today-ndogo-mkt', name: 'TODAY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'toe-mkt', name: 'TOE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'toe-ndogo-mkt', name: 'TOE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'together-mkt', name: 'TOGETHER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'together-ndogo-mkt', name: 'TOGETHER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'told-mkt', name: 'TOLD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'told-ndogo-mkt', name: 'TOLD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'tomato-mkt', name: 'TOMATO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'tomato-ndogo-mkt', name: 'TOMATO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tomorrow-mkt', name: 'TOMORROW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'tomorrow-ndogo-mkt', name: 'TOMORROW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
