import { Product } from './types';

export const MARKET_PRODUCTS_5: Product[] = [
  { id: 'mkorogo-mkt', name: 'MKOROGO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mkorogo-ndogo-mkt', name: 'MKOROGO NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mlezi-mkt', name: 'MLEZI', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mlezi-ndogo-mkt', name: 'MLEZI NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mlo-mkt', name: 'MLO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mlo-ndogo-mkt', name: 'MLO NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mo-extra-mkt', name: 'MO EXTRA', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-extra-ndogo-mkt', name: 'MO EXTRA NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-juice-mkt', name: 'MO JUICE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-juice-ndogo-mkt', name: 'MO JUICE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-malt-mkt', name: 'MO MALT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-malt-ndogo-mkt', name: 'MO MALT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-nectar-mkt', name: 'MO NECTAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-nectar-ndogo-mkt', name: 'MO NECTAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-orange-mkt', name: 'MO ORANGE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-orange-ndogo-mkt', name: 'MO ORANGE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-pineapple-mkt', name: 'MO PINEAPPLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-pineapple-ndogo-mkt', name: 'MO PINEAPPLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mo-water-mkt', name: 'MO WATER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mo-water-ndogo-mkt', name: 'MO WATER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mop-mkt', name: 'MOP', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mop-ndogo-mkt', name: 'MOP NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-coil-mkt', name: 'MOSQUITO COIL', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-coil-ndogo-mkt', name: 'MOSQUITO COIL NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-net-mkt', name: 'MOSQUITO NET', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-net-ndogo-mkt', name: 'MOSQUITO NET NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-spray-mkt', name: 'MOSQUITO SPRAY', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mosquito-spray-ndogo-mkt', name: 'MOSQUITO SPRAY NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mouthwash-mkt', name: 'MOUTHWASH', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mouthwash-ndogo-mkt', name: 'MOUTHWASH NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'moyo-mkt', name: 'MOYO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'moyo-ndogo-mkt', name: 'MOYO NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mpira-mkt', name: 'MPIRA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mpira-ndogo-mkt', name: 'MPIRA NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'mshumaa-mkt', name: 'MSHUMAA', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mshumaa-ndogo-mkt', name: 'MSHUMAA NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'mtama-mkt', name: 'MTAMA', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'mtama-ndogo-mkt', name: 'MTAMA NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mtindi-mkt', name: 'MTINDI', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'mtindi-ndogo-mkt', name: 'MTINDI NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'mto-mkt', name: 'MTO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mto-ndogo-mkt', name: 'MTO NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'muhogo-mkt', name: 'MUHOGO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'muhogo-ndogo-mkt', name: 'MUHOGO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'mwavuli-mkt', name: 'MWAVULI', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'mwavuli-ndogo-mkt', name: 'MWAVULI NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'mzigo-mkt', name: 'MZIGO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'mzigo-ndogo-mkt', name: 'MZIGO NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'nadi-mkt', name: 'NADI', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'nadi-ndogo-mkt', name: 'NADI NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'nazi-mkt', name: 'NAZI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'nazi-ndogo-mkt', name: 'NAZI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ndimu-mkt', name: 'NDIMU', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ndimu-ndogo-mkt', name: 'NDIMU NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ndizi-mkt', name: 'NDIZI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'ndizi-ndogo-mkt', name: 'NDIZI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'neema-mkt', name: 'NEEMA', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'neema-ndogo-mkt', name: 'NEEMA NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'nescafe-mkt', name: 'NESCAFE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'nescafe-ndogo-mkt', name: 'NESCAFE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'nguo-mkt', name: 'NGUO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'nguo-ndogo-mkt', name: 'NGUO NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'nido-mkt', name: 'NIDO', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'nido-ndogo-mkt', name: 'NIDO NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'njugu-mkt', name: 'NJUGU', category: 'African Market', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'njugu-ndogo-mkt', name: 'NJUGU NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'nundu-mkt', name: 'NUNDU', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true },
  { id: 'nyama-mkt', name: 'NYAMA', category: 'Butchery', price: 17000, unit: 'kg', isAvailable: true },
  { id: 'nyanya-mkt', name: 'NYANYA', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'nyanya-ndogo-mkt', name: 'NYANYA NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'oat-mkt', name: 'OAT', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'oat-ndogo-mkt', name: 'OAT NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'oil-mkt', name: 'OIL', category: 'African Market', price: 9000, unit: '1L', isAvailable: true },
  { id: 'oil-ndogo-mkt', name: 'OIL NDOGO', category: 'African Market', price: 1500, unit: 'pc', isAvailable: true },
  { id: 'ok-mkt', name: 'OK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ok-ndogo-mkt', name: 'OK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'omo-mkt', name: 'OMO', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'omo-ndogo-mkt', name: 'OMO NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
  { id: 'orange-mkt', name: 'ORANGE', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'orange-ndogo-mkt', name: 'ORANGE NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'oreo-mkt', name: 'OREO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'oreo-ndogo-mkt', name: 'OREO NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ovado-mkt', name: 'OVADO', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'ovado-ndogo-mkt', name: 'OVADO NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ovaltine-mkt', name: 'OVALTINE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'ovaltine-ndogo-mkt', name: 'OVALTINE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'pads-mkt', name: 'PADS', category: 'Specialty', price: 4000, unit: 'pc', isAvailable: true },
  { id: 'pads-ndogo-mkt', name: 'PADS NDOGO', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'panadol-mkt', name: 'PANADOL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'panadol-ndogo-mkt', name: 'PANADOL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'panga-mkt', name: 'PANGA', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'panga-ndogo-mkt', name: 'PANGA NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'pampers-mkt', name: 'PAMPERS', category: 'Specialty', price: 55000, unit: 'pc', isAvailable: true },
  { id: 'pampers-ndogo-mkt', name: 'PAMPERS NDOGO', category: 'Specialty', price: 23000, unit: 'pc', isAvailable: true },
  { id: 'paprika-mkt', name: 'PAPRIKA', category: 'Specialty', price: 6000, unit: 'pc', isAvailable: true },
  { id: 'paprika-ndogo-mkt', name: 'PAPRIKA NDOGO', category: 'Specialty', price: 3000, unit: 'pc', isAvailable: true },
  { id: 'parachichi-mkt', name: 'PARACHICHI', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'parachichi-ndogo-mkt', name: 'PARACHICHI NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'parazone-mkt', name: 'PARAZONE', category: 'Specialty', price: 5000, unit: 'pc', isAvailable: true },
  { id: 'parazone-ndogo-mkt', name: 'PARAZONE NDOGO', category: 'Specialty', price: 2500, unit: 'pc', isAvailable: true },
];
