import { Product } from './types';

export const MARKET_PRODUCTS_15: Product[] = [
  { id: 'ulimu-mkt', name: 'ULIMU', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ulimu-ndogo-mkt', name: 'ULIMU NDOGO', category: 'African Market', price: 500, unit: 'pc', isAvailable: true },
  { id: 'uncle-mkt', name: 'UNCLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'uncle-ndogo-mkt', name: 'UNCLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'under-mkt', name: 'UNDER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'under-ndogo-mkt', name: 'UNDER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'underline-mkt', name: 'UNDERLINE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'underline-ndogo-mkt', name: 'UNDERLINE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'understand-mkt', name: 'UNDERSTAND', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'understand-ndogo-mkt', name: 'UNDERSTAND NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'unit-mkt', name: 'UNIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'unit-ndogo-mkt', name: 'UNIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'universe-mkt', name: 'UNIVERSE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'universe-ndogo-mkt', name: 'UNIVERSE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'unknown-mkt', name: 'UNKNOWN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'unknown-ndogo-mkt', name: 'UNKNOWN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'unless-mkt', name: 'UNLESS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'unless-ndogo-mkt', name: 'UNLESS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'until-mkt', name: 'UNTIL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'until-ndogo-mkt', name: 'UNTIL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'unusual-mkt', name: 'UNUSUAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'unusual-ndogo-mkt', name: 'UNUSUAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'up-mkt', name: 'UP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'up-ndogo-mkt', name: 'UP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'upon-mkt', name: 'UPON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'upon-ndogo-mkt', name: 'UPON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'upper-mkt', name: 'UPPER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'upper-ndogo-mkt', name: 'UPPER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'upward-mkt', name: 'UPWARD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'upward-ndogo-mkt', name: 'UPWARD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'us-mkt', name: 'US', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'us-ndogo-mkt', name: 'US NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'use-mkt', name: 'USE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'use-ndogo-mkt', name: 'USE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'useful-mkt', name: 'USEFUL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'useful-ndogo-mkt', name: 'USEFUL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'using-mkt', name: 'USING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'using-ndogo-mkt', name: 'USING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'usual-mkt', name: 'USUAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'usual-ndogo-mkt', name: 'USUAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'usually-mkt', name: 'USUALLY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'usually-ndogo-mkt', name: 'USUALLY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'v-mkt', name: 'V', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'v-ndogo-mkt', name: 'V NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'valley-mkt', name: 'VALLEY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'valley-ndogo-mkt', name: 'VALLEY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'valuable-mkt', name: 'VALUABLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'valuable-ndogo-mkt', name: 'VALUABLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'value-mkt', name: 'VALUE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'value-ndogo-mkt', name: 'VALUE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vapor-mkt', name: 'VAPOR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vapor-ndogo-mkt', name: 'VAPOR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'variety-mkt', name: 'VARIETY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'variety-ndogo-mkt', name: 'VARIETY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'various-mkt', name: 'VARIOUS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'various-ndogo-mkt', name: 'VARIOUS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vast-mkt', name: 'VAST', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vast-ndogo-mkt', name: 'VAST NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vegetable-mkt', name: 'VEGETABLE', category: 'African Market', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'vegetable-ndogo-mkt', name: 'VEGETABLE NDOGO', category: 'African Market', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'verb-mkt', name: 'VERB', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'verb-ndogo-mkt', name: 'VERB NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vertical-mkt', name: 'VERTICAL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vertical-ndogo-mkt', name: 'VERTICAL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'very-mkt', name: 'VERY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'very-ndogo-mkt', name: 'VERY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vessel-mkt', name: 'VESSEL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vessel-ndogo-mkt', name: 'VESSEL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'victory-mkt', name: 'VICTORY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'victory-ndogo-mkt', name: 'VICTORY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'view-mkt', name: 'VIEW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'view-ndogo-mkt', name: 'VIEW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'village-mkt', name: 'VILLAGE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'village-ndogo-mkt', name: 'VILLAGE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'visit-mkt', name: 'VISIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'visit-ndogo-mkt', name: 'VISIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'visitor-mkt', name: 'VISITOR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'visitor-ndogo-mkt', name: 'VISITOR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'voice-mkt', name: 'VOICE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'voice-ndogo-mkt', name: 'VOICE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'volume-mkt', name: 'VOLUME', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'volume-ndogo-mkt', name: 'VOLUME NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vote-mkt', name: 'VOTE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vote-ndogo-mkt', name: 'VOTE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'vowel-mkt', name: 'VOWEL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'vowel-ndogo-mkt', name: 'VOWEL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'voyage-mkt', name: 'VOYAGE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'voyage-ndogo-mkt', name: 'VOYAGE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'w-mkt', name: 'W', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'w-ndogo-mkt', name: 'W NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wagon-mkt', name: 'WAGON', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wagon-ndogo-mkt', name: 'WAGON NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wait-mkt', name: 'WAIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wait-ndogo-mkt', name: 'WAIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'walk-mkt', name: 'WALK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'walk-ndogo-mkt', name: 'WALK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'wall-mkt', name: 'WALL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'wall-ndogo-mkt', name: 'WALL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'want-mkt', name: 'WANT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'want-ndogo-mkt', name: 'WANT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
