import { Product } from './types';

export const MARKET_PRODUCTS_9: Product[] = [
  { id: 'sheep-mkt', name: 'SHEEP', category: 'Butchery', price: 16000, unit: 'kg', isAvailable: true },
  { id: 'sheet-mkt', name: 'SHEET', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sheet-ndogo-mkt', name: 'SHEET NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shelf-mkt', name: 'SHELF', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'shelf-ndogo-mkt', name: 'SHELF NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'shell-mkt', name: 'SHELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shell-ndogo-mkt', name: 'SHELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shine-mkt', name: 'SHINE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shine-ndogo-mkt', name: 'SHINE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'ship-mkt', name: 'SHIP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'ship-ndogo-mkt', name: 'SHIP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shirt-mkt', name: 'SHIRT', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'shirt-ndogo-mkt', name: 'SHIRT NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'shoe-mkt', name: 'SHOE', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'shoe-ndogo-mkt', name: 'SHOE NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'shop-mkt', name: 'SHOP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shop-ndogo-mkt', name: 'SHOP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shore-mkt', name: 'SHORE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shore-ndogo-mkt', name: 'SHORE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'short-mkt', name: 'SHORT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'short-ndogo-mkt', name: 'SHORT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shot-mkt', name: 'SHOT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shot-ndogo-mkt', name: 'SHOT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'should-mkt', name: 'SHOULD', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'should-ndogo-mkt', name: 'SHOULD NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shoulder-mkt', name: 'SHOULDER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shoulder-ndogo-mkt', name: 'SHOULDER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shout-mkt', name: 'SHOUT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shout-ndogo-mkt', name: 'SHOUT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'show-mkt', name: 'SHOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'show-ndogo-mkt', name: 'SHOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'shower-mkt', name: 'SHOWER', category: 'Specialty', price: 15000, unit: 'pc', isAvailable: true },
  { id: 'shower-ndogo-mkt', name: 'SHOWER NDOGO', category: 'Specialty', price: 10000, unit: 'pc', isAvailable: true },
  { id: 'shut-mkt', name: 'SHUT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'shut-ndogo-mkt', name: 'SHUT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sick-mkt', name: 'SICK', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sick-ndogo-mkt', name: 'SICK NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'side-mkt', name: 'SIDE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'side-ndogo-mkt', name: 'SIDE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sight-mkt', name: 'SIGHT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sight-ndogo-mkt', name: 'SIGHT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sign-mkt', name: 'SIGN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sign-ndogo-mkt', name: 'SIGN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'silent-mkt', name: 'SILENT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'silent-ndogo-mkt', name: 'SILENT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'silver-mkt', name: 'SILVER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'silver-ndogo-mkt', name: 'SILVER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'similar-mkt', name: 'SIMILAR', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'similar-ndogo-mkt', name: 'SIMILAR NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'simple-mkt', name: 'SIMPLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'simple-ndogo-mkt', name: 'SIMPLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'since-mkt', name: 'SINCE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'since-ndogo-mkt', name: 'SINCE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sing-mkt', name: 'SING', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sing-ndogo-mkt', name: 'SING NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'single-mkt', name: 'SINGLE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'single-ndogo-mkt', name: 'SINGLE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sister-mkt', name: 'SISTER', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sister-ndogo-mkt', name: 'SISTER NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sit-mkt', name: 'SIT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sit-ndogo-mkt', name: 'SIT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'six-mkt', name: 'SIX', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'six-ndogo-mkt', name: 'SIX NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'size-mkt', name: 'SIZE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'size-ndogo-mkt', name: 'SIZE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'skin-mkt', name: 'SKIN', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'skin-ndogo-mkt', name: 'SKIN NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sky-mkt', name: 'SKY', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sky-ndogo-mkt', name: 'SKY NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'slabs-mkt', name: 'SLABS', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'slabs-ndogo-mkt', name: 'SLABS NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'slave-mkt', name: 'SLAVE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'slave-ndogo-mkt', name: 'SLAVE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'sleep-mkt', name: 'SLEEP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'sleep-ndogo-mkt', name: 'SLEEP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'slip-mkt', name: 'SLIP', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'slip-ndogo-mkt', name: 'SLIP NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'slow-mkt', name: 'SLOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'slow-ndogo-mkt', name: 'SLOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'small-mkt', name: 'SMALL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'small-ndogo-mkt', name: 'SMALL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'smell-mkt', name: 'SMELL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'smell-ndogo-mkt', name: 'SMELL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'smile-mkt', name: 'SMILE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'smile-ndogo-mkt', name: 'SMILE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'smoke-mkt', name: 'SMOKE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'smoke-ndogo-mkt', name: 'SMOKE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'smooth-mkt', name: 'SMOOTH', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'smooth-ndogo-mkt', name: 'SMOOTH NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'snake-mkt', name: 'SNAKE', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'snake-ndogo-mkt', name: 'SNAKE NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'snow-mkt', name: 'SNOW', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'snow-ndogo-mkt', name: 'SNOW NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'so-mkt', name: 'SO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'so-ndogo-mkt', name: 'SO NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soap-mkt', name: 'SOAP', category: 'Specialty', price: 2000, unit: 'pc', isAvailable: true },
  { id: 'soap-ndogo-mkt', name: 'SOAP NDOGO', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soft-mkt', name: 'SOFT', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soft-ndogo-mkt', name: 'SOFT NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
  { id: 'soil-mkt', name: 'SOIL', category: 'Specialty', price: 1000, unit: 'pc', isAvailable: true },
  { id: 'soil-ndogo-mkt', name: 'SOIL NDOGO', category: 'Specialty', price: 500, unit: 'pc', isAvailable: true },
];
